import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {browserConfig} from './browser-config.mjs';
const config=browserConfig(import.meta.url),stamp=new Date().toISOString().replace(/[^0-9TZ]/g,'');
const output=resolve(config.output,process.env.HH_VERIFY_RUN||`flows-${stamp}`),leaf=config.leaf||`${config.preview}/compiled/hh/index.html`;
await mkdir(output,{recursive:true});
const receipt={schema:'hh-independent-browser-flows.v1',createdAt:new Date().toISOString(),leaf,builtRoot:config.builtRoot,checks:[],console:[],requests:[],sourceStable:false,boundary:'Every account/form/community transition uses actual DOM controls. Script reads state only; no injected authentication or direct controller dispatch.'};
async function pins(){const result={};for(const folder of ['checkpoint/vendor/hh/src',config.builtRoot]){try{for(const name of (await readdir(resolve(config.root,folder))).sort()){if(!/\.(mjs|css|html)$/.test(name))continue;const path=resolve(config.root,folder,name);result[relative(config.root,path)]=createHash('sha256').update(await readFile(path)).digest('hex')}}catch(error){result[folder]=String(error)}}return result}
receipt.sourceHashes=await pins();
const {chromium}=await import(pathToFileURL(config.playwrightPath).href),browser=await chromium.launch(config.launch);
let page;
async function check(name,fn){try{const details=await fn();receipt.checks.push({name,passed:true,details:details??null});console.log(JSON.stringify({check:name,passed:true}));return true}catch(error){const path=resolve(output,`${name.replace(/[^a-z0-9]+/gi,'-')}-failed.png`);await page?.screenshot({path,fullPage:true}).catch(()=>{});receipt.checks.push({name,passed:false,error:String(error.stack).slice(0,3000),screenshot:relative(config.root,path)});console.log(JSON.stringify({check:name,passed:false,error:String(error.message)}));if(page&&await page.locator('[role=dialog]').count())await page.keyboard.press('Escape').catch(()=>{});return false}}
async function open(path){const url=`${leaf}#${path}`;if(page.url()!==url)await page.goto(url,{waitUntil:'networkidle',timeout:15000});await page.locator('.hh-public-site').waitFor({timeout:8000});await page.evaluate(()=>document.fonts.ready)}
async function text(pattern){await page.waitForFunction(([source,flags])=>new RegExp(source,flags).test(document.body.innerText),[pattern.source,pattern.flags],{timeout:5000})}
async function school(form){for(const [key,value] of [['state','Demo Washington'],['county','Demo King'],['district','Demo District'],['school','Demo Academy']]){const control=form.locator(`[data-public-select='${key}']`);await control.locator(`option[value='${value}']`).waitFor({state:'attached'});await control.selectOption(value)}}
async function fill(form,name,value){await form.locator(`[name='${name}']`).fill(value)}
async function reveal(control){const details=control.locator('xpath=ancestor::details[1]');if(await details.count()&&!await details.evaluate(e=>e.open))await details.locator('summary').first().click()}
async function previewControls(){const details=page.locator('details.community-preview-controls');if(!await details.evaluate(e=>e.open))await details.locator('summary').click()}
async function previewRole(value){await previewControls();await page.locator('[data-event=forum-role]').selectOption(value)}
const password='Independent-DOM-Password-47',email='jordan.browser@example.test';
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});context.setDefaultTimeout(8000);page=await context.newPage();
 page.on('console',m=>receipt.console.push({type:m.type(),text:m.text().slice(0,2000)}));page.on('pageerror',e=>receipt.console.push({type:'pageerror',text:String(e).slice(0,2000)}));page.on('request',r=>receipt.requests.push({url:r.url(),method:r.method(),resourceType:r.resourceType()}));
 await check('register-terms-focus-close-preserves-input',async()=>{
  await open('/register');const form=page.locator('#hh-register-form');const nameField=form.locator('[name=name]');await nameField.fill('');await nameField.pressSequentially('Jordan Browser');assert.equal(await nameField.inputValue(),'Jordan Browser');await fill(form,'email',email);await fill(form,'password',password);await fill(form,'confirmPassword',password);
  assert.equal(await form.locator('[name=name]').isEditable(),true);await page.locator('#hh-terms-open').click();const dialog=page.locator('[role=dialog]');await dialog.waitFor();
  assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('[role=dialog]')),true,'Opening Terms must move focus into dialog');
  const scrollIndex=await dialog.evaluate(root=>[...root.querySelectorAll('*')].findIndex(e=>/auto|scroll/.test(getComputedStyle(e).overflowY)&&e.scrollHeight>e.clientHeight+1&&e.clientHeight>100));assert.ok(scrollIndex>=0,'Terms must contain a scrollable legal document');const scrollTarget=dialog.locator('*').nth(scrollIndex),box=await scrollTarget.boundingBox();assert.ok(box);await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.wheel(0,300);await page.waitForFunction(index=>{const root=document.querySelector('[role=dialog]');return root?.querySelectorAll('*')[index]?.scrollTop>0},scrollIndex);
  for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('[role=dialog]')),true,'Tab escaped modal')}
  await page.screenshot({path:resolve(output,'register-terms-desktop.png'),fullPage:true});await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#hh-terms-open').evaluate(e=>e===document.activeElement),true);
  assert.equal(await form.locator('[name=name]').inputValue(),'Jordan Browser');assert.equal(await form.locator('[name=password]').inputValue(),password,'Opening/closing Terms erased typed password');
  await page.locator('#hh-terms-open').click();const close=page.getByRole('button',{name:'Close terms',exact:true});assert.equal(await close.evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===e||e.contains(hit)}),true,'Terms Close center must receive pointer hit');await close.click();await dialog.waitFor({state:'hidden'});
  await page.locator('#hh-public-nav-toggle').click();assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'true');await page.locator('#hh-terms-open').click();await dialog.waitFor();await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'true','Terms consumes Escape before Menu');await page.keyboard.press('Escape');assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('#hh-public-nav-toggle').evaluate(e=>e===document.activeElement),true);
 });
 let registered=false,loggedIn=false,created=false;
 await check('editable-registration-confirmation-and-pending-submit',async()=>{
  await open('/register');const form=page.locator('#hh-register-form');await fill(form,'name','Jordan Browser');await fill(form,'email',email);await fill(form,'phone','555-0183');await fill(form,'password',password);await fill(form,'confirmPassword','Mismatch');await school(form);await page.locator('#hh-terms-consent').check();await page.locator('#hh-register-submit').click();await text(/confirmation.*match|passwords.*match/i);
  await fill(form,'password',password);await fill(form,'confirmPassword',password);await page.locator('#hh-register-submit').click();await text(/pending/i);registered=true;await page.screenshot({path:resolve(output,'registered-pending.png'),fullPage:true});
 });
 await check('pending-login-denial-approval-actual-login',async()=>{
  assert.ok(registered,'Registration prerequisite failed');await open('/login');const form=page.locator('#hh-login-form');await fill(form,'email',email);await fill(form,'password',password);await page.locator('#hh-login-submit').click();await text(/pending|not.*approved/i);
  await open('/register');await page.locator('#hh-register-approve').click();await page.waitForFunction(()=>window.hhPreview?.state.journey.runtime.registration.status==='approved');await text(/approval.*simulated|approved/i);await open('/login');await fill(form,'email',email);await fill(form,'password',password);await page.locator('#hh-login-submit').click();await page.locator('#hh-profile-create-form').waitFor();loggedIn=true;
 });
 await check('create-edit-public-profile-natural-journey',async()=>{
  assert.ok(loggedIn,'Login prerequisite failed');let form=page.locator('#hh-profile-create-form');await fill(form,'name','Jordan Browser');await fill(form,'bio','An independent local classroom introduction.');await fill(form,'wishlistUrl','https://www.amazon.com/hz/wishlist/ls/DEMO-INDEPENDENT');await form.locator('[type=submit]').click();await page.locator('#hh-profile-edit').waitFor();created=true;
  await page.locator('#hh-profile-edit').click();form=page.locator('#hh-profile-edit-form');for(const [name,value] of [['name','Jordan Browser Edited'],['bio','A changed public classroom introduction.']]){const field=form.locator(`[name=${name}]`);await field.fill('');await field.pressSequentially(value);assert.equal(await field.inputValue(),value)}await form.locator('[type=submit]').click();await text(/Jordan Browser Edited/);
  if(!/\/(?:public-profile|teachers)\//.test(new URL(page.url()).hash))await page.getByRole('link',{name:/public.*profile|view.*public/i}).first().click();
  assert.match(new URL(page.url()).hash,/\/(?:public-profile|teachers)\//);await text(/Jordan Browser Edited/);await text(/A changed public classroom introduction\./);await text(/Demo Academy/);await text(/Demo King/);await text(/Demo Washington/);assert.equal((await page.locator('main').innerText()).includes('[object Object]'),false);await page.screenshot({path:resolve(output,'edited-public-profile.png'),fullPage:true});
 });
 await check('wishlist-share-local-handoff',async()=>{
  assert.ok(created,'Profile prerequisite failed');await page.locator('#hh-profile-wishlist').click();await page.waitForFunction(()=>window.hhPreview?.state.journey.wishlist.intent===true);const wishlist=await page.evaluate(()=>window.hhPreview.state.journey.wishlist);assert.equal(wishlist.remote,false);assert.match(wishlist.destination,/^https:\/\/www\.amazon\.com\/hz\/wishlist\/ls\//);
  await page.locator('#hh-profile-share').click();await page.waitForFunction(()=>window.hhPreview?.state.journey.share.intent===true);const share=await page.evaluate(()=>window.hhPreview.state.journey.share);assert.match(share.url,/\/(?:public-profile|teachers)\//);assert.equal(await page.locator('[name=share-route]').inputValue(),share.url);await text(/share|copied|profile link/i);return {wishlist,share,url:page.url(),outgoingNetworkRequests:receipt.requests.filter(r=>new URL(r.url).origin!==new URL(leaf).origin)};
 });
 await check('directory-cascade-clear-match-empty-remember',async()=>{
  await open('/directory');const form=page.locator('#hh-directory-form');await school(form);await page.locator('#hh-directory-search').click();await page.locator('#hh-directory-results a').first().waitFor();
  await form.locator('[data-public-select=state]').selectOption('');for(const key of ['county','district','school']){assert.equal(await form.locator(`[data-public-select=${key}]`).inputValue(),'');assert.equal(await form.locator(`[data-public-select=${key}] option`).count(),1)}
  await school(form);const query=form.locator('[name=query]');await reveal(query);await query.fill('');await query.pressSequentially('A certainly nonexistent classroom');assert.equal(await query.inputValue(),'A certainly nonexistent classroom');assert.equal(await query.isVisible(),true,'Typing must preserve advanced search disclosure');await page.locator('#hh-directory-search').click();await text(/no teacher|0 teacher|no.*match/i);await open('/about');await open('/directory');const remembered=page.locator('#hh-directory-form [name=query]');assert.equal(await remembered.inputValue(),'A certainly nonexistent classroom');
 });
 await check('contact-counter-validation-unsent-reset-form',async()=>{
  await open('/contact');const form=page.locator('#hh-contact-form');await fill(form,'message','Independent 20 chars');assert.equal('Independent 20 chars'.length,20);assert.match(await page.locator('#hh-contact-counter').innerText(),/230/);
  assert.equal(await form.locator('[name=message]').getAttribute('maxlength'),'250');await fill(form,'name','Independent Guest');await fill(form,'email','guest@example.test');await fill(form,'subject','A local test note');await page.locator('#hh-contact-submit').click();await text(/nothing was sent|not.*sent|unsent/i);
  await open('/forgot');const reset=page.locator('#hh-forgot-form');await fill(reset,'email','guest@example.test');await reset.locator('[type=submit]').click();await text(/no.*email|not.*send|nothing.*sent|local.*preview/i);
 });
 await check('about-portraits-terms-partner-contact-links',async()=>{
  await open('/about');assert.equal(await page.locator('.hh-team-grid img').count(),6);await page.locator('#hh-about-terms').click();await page.locator('[role=dialog]').waitFor();await page.keyboard.press('Escape');
  await open('/partners');assert.equal(await page.locator('.hh-partner-grid img,.hh-partner img').count(),5);await page.locator('main a[data-public-route=contact]').first().click();await page.locator('#hh-contact-form').waitFor();
 });
 const savedDesktopPage=page;const homeContext=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});homeContext.setDefaultTimeout(8000);page=await homeContext.newPage();page.on('console',m=>receipt.console.push({type:m.type(),text:m.text().slice(0,2000)}));page.on('pageerror',e=>receipt.console.push({type:'pageerror',text:String(e).slice(0,2000)}));page.on('request',r=>receipt.requests.push({url:r.url(),method:r.method(),resourceType:r.resourceType()}));
 await check('home-primary-actions-reference-random-local-donation',async()=>{
  await open('/');await page.locator('#hh-home-find-teachers').click();await page.locator('#hh-directory-form').waitFor();assert.equal((await page.locator('.hh-directory-results-card').innerText()).trim(),'Search Results','Initial directory must not claim a performed empty search');await open('/');await page.locator('#hh-home-register').click();await page.locator('#hh-register-form').waitFor();
  await open('/');const before=await page.evaluate(()=>window.hhPreview.state.journey.runtime);await page.getByRole('link',{name:/view.*(?:teacher|profile)/i}).first().click();await page.waitForURL(/reference-sarah/);await page.waitForFunction(()=>document.querySelector('.hh-public-site')?.dataset.publicPage==='profile'&&window.hhPreview?.state.route.profileId==='reference-sarah');await page.getByRole('heading',{name:'Sarah Endsley',exact:true}).waitFor();await page.evaluate(()=>new Promise(requestAnimationFrame));assert.equal(await page.evaluate(()=>scrollY),0,'Genuine completed route navigation must reset old Home scroll');assert.equal(await page.evaluate(()=>document.activeElement.id),'hh-main');await page.locator('details').filter({has:page.getByText('Captured reference source',{exact:true})}).locator('summary').click();await text(/captured.*reference|reference.*snapshot/i);assert.deepEqual(await page.evaluate(()=>window.hhPreview.state.journey.runtime),before,'Readonly captured public profile must not mutate fixture account state');
  await open('/');await page.locator('#hh-home-random-teacher').click();await page.locator('#hh-profile-wishlist').waitFor();const profile=await page.evaluate(()=>window.hhPreview.state.journey.profile);assert.equal(profile.status,'present');assert.ok(profile.value?.id||profile.value?.teacherId);
  await open('/');const previous=await page.evaluate(()=>JSON.stringify(window.hhPreview.state.journey.outcome));await page.locator('#hh-home-donate').click();await text(/no.*payment|not.*payment|local.*donation|donation.*preview/i);const outcome=await page.evaluate(()=>window.hhPreview.state.journey.outcome);assert.notEqual(JSON.stringify(outcome),previous,'Donate must produce a local handoff outcome');assert.equal(outcome.remote,false);return {referenceReadOnly:true,randomProfileId:profile.value.id||profile.value.teacherId,donation:outcome};
 });await homeContext.close();page=savedDesktopPage;
 await check('secrets-never-saved',async()=>{
  const values=await page.evaluate(()=>Object.keys(sessionStorage).map(key=>({key,hasPassword:sessionStorage.getItem(key).includes('Independent-DOM-Password-47')})));
  const inspected=await page.evaluate(()=>({available:!!window.hhPreview,stateHasPassword:JSON.stringify(window.hhPreview?.state||{}).includes('Independent-DOM-Password-47'),runtimeHasPassword:JSON.stringify(window.hhPreview?.runtime||{}).includes('Independent-DOM-Password-47')}));
  assert.equal(inspected.available,true,'Read-only actual runtime inspection unavailable');assert.equal(inspected.stateHasPassword,false);assert.equal(inspected.runtimeHasPassword,false);assert.equal(values.some(x=>x.hasPassword),false);assert.equal(receipt.console.some(x=>x.text.includes(password)),false);return {storageKeys:values.map(x=>x.key),passwordSaved:false,...inspected};
 });
 await check('forum-actual-create-reply-search-vote-report-hide-persistence',async()=>{
  await open('/forum');await previewRole('teacher');await page.locator('[data-event=forum-compose-topic]').click();let form=page.locator('form[data-submit=forum-topic]');await fill(form,'title','Independent DOM classroom topic');await fill(form,'content','This local discussion is about a literal fraction example.');await form.locator('[name=category]').selectOption('Questions');await form.locator('[type=submit]').click();await text(/Independent DOM classroom topic/);
  if(!await page.locator('form[data-submit=forum-reply]').count())await page.getByRole('link',{name:'Independent DOM classroom topic',exact:true}).click();
  form=page.locator('form[data-submit=forum-reply]');await form.locator('textarea').fill('A unique independent reply: mangosteen.');await form.locator('[type=submit]').click();await text(/mangosteen/);await page.locator('[data-event=forum-vote]').first().click();await page.waitForFunction(()=>window.hhPreview.state.community.threads.some(t=>t.title==='Independent DOM classroom topic'&&t.votes.length===1));await page.locator('[data-event=forum-flag-thread]').click();await page.waitForFunction(()=>window.hhPreview.state.community.threads.some(t=>t.title==='Independent DOM classroom topic'&&t.reported===true));assert.equal(await page.locator('[data-event=forum-flag-thread]').count(),0);
  const id=await page.locator('[data-event=forum-hide-thread],[data-event=forum-flag-thread],[data-event=forum-edit-post]').first().getAttribute('data-thread-id');assert.ok(id);
  await open('/forum');await page.locator(`.community-topic[data-thread-id='${id}'] .community-reported`).waitFor();await page.locator('[data-event=forum-search]').fill('mangosteen');await page.locator('.community-topic').first().waitFor();assert.equal(await page.locator('.community-topic').count(),1);await page.locator('[data-event=forum-clear-search]').click();await page.locator('[data-event=forum-sort][data-sort=date-oldest]').click();await page.locator('[data-event=forum-sort][data-sort=upvotes]').click();
  await page.locator(`[data-event=forum-open-thread][data-thread-id='${id}']`).first().click();await previewRole('moderator');await page.locator(`[data-event=forum-hide-thread][data-thread-id='${id}']`).click();await previewRole('anonymous');await text(/conversation.*unavailable|topic.*unavailable/i);assert.equal((await page.locator('main').innerText()).includes('mangosteen'),false,'Hidden discussion body must not be rendered to Visitor');await open('/forum');assert.equal(await page.locator(`.community-topic[data-thread-id='${id}']`).count(),0);
  await page.reload({waitUntil:'networkidle'});await page.locator('.hh-public-site').waitFor();assert.equal(await page.locator(`.community-topic[data-thread-id='${id}']`).count(),0);await previewRole('moderator');assert.equal(await page.locator(`.community-topic[data-thread-id='${id}']`).count(),1);await page.locator(`[data-event=forum-open-thread][data-thread-id='${id}']`).first().click();await page.locator(`[data-event=forum-unhide-thread][data-thread-id='${id}']`).click();await previewRole('anonymous');await open('/forum');assert.equal(await page.locator(`.community-topic[data-thread-id='${id}']`).count(),1);await page.screenshot({path:resolve(output,'forum-local-actual-flow.png'),fullPage:true});
  return {threadId:id,teacherModeration:'explicit authored preview role; production authority unobserved'};
 });
 await check('diagnostic-failure-retry-logout-reset-actual-controls',async()=>{
  assert.equal(await page.locator('summary').filter({hasText:/^Preview tools$/}).count(),1,'One persistent Preview tools disclosure');assert.equal(await page.getByText('© 2024 Homeroom Heroes. All rights reserved.',{exact:true}).count(),1,'One public copyright');
  await open('/directory');const form=page.locator('#hh-directory-form');await school(form);const query=form.locator('[name=query]');await reveal(query);await query.fill('Avery');
  const failure=page.locator('[data-event="public:fail-next"],[data-event="arm-failure"]').first();await reveal(failure);await failure.click();await page.locator('#hh-directory-search').click();await page.locator('#hh-directory-retry').waitFor();await text(/could not be loaded|local.*fail|read.*failed/i);
  await page.locator('#hh-directory-retry').click();await text(/Demo Avery/);await page.waitForFunction(()=>window.hhPreview.state.journey.matches.items.some(p=>p.id==='demo-avery'));assert.equal(await page.locator('#hh-directory-retry').count(),0,'Recovered result must not retain stale Retry');
  const logout=page.locator('[data-event="public:logout"],[data-event="logout"]').first();await reveal(logout);if(!await logout.isVisible())await page.locator('#hh-public-nav-toggle').click();await logout.click();await page.waitForFunction(()=>window.hhPreview.state.journey.runtime.session.status==='anonymous');
  const reset=page.locator('[data-event="public:reset"],[data-event="reset"]').first();await reveal(reset);await reset.click();await page.waitForFunction(()=>window.hhPreview.state.journey.runtime.registration.status==='none');const fresh=await page.evaluate(()=>window.hhPreview.state.journey);assert.equal(fresh.runtime.session.status,'anonymous');assert.equal(fresh.runtime.registration.status,'none');assert.equal(fresh.terms.accepted,false);assert.equal(fresh.school.school,'');assert.equal(fresh.registration.identity.name,'');await page.getByRole('link',{name:'Sign Up',exact:true}).first().click();await page.locator('#hh-register-form').waitFor();assert.equal(await page.locator('#hh-register-form [name=name]').inputValue(),'');
  return {fault:'Actual local preview fault button, followed by actual Retry; no service/state injection.',logout:'Actual control',reset:'Actual control clears sample registration, consent and display identity.'};
 });
 await check('original-devtools-survives-public-navigation',async()=>{
  const disclosure=page.locator('#hh-preview-tools');if(!await disclosure.evaluate(e=>e.open))await disclosure.locator(':scope > summary').click();const host=await page.locator('#hh-devtools-mount').elementHandle(),nav=await page.locator('.pxdt-nav').elementHandle(),panel=await page.locator('.pxdt').elementHandle();assert.ok(host&&nav&&panel);await page.locator('.pxdt-nav').getByRole('button',{name:'PxC DevTools',exact:true}).click();await page.locator('.pxdt').waitFor();assert.equal(await page.locator('.pxdt [data-devtools-mutation]').count(),0,'Inspector remains read-only');
  await page.getByRole('link',{name:'About',exact:true}).first().click();await page.waitForURL(/#\/about$/);await page.getByRole('heading',{name:'About Us',exact:true}).waitFor();assert.equal(await page.locator('.hh-team-grid img').count(),6);for(const handle of [host,nav,panel])assert.equal(await handle.evaluate(node=>node.isConnected),true,'Original DevTools node was replaced on route render');assert.equal(await page.locator('summary').filter({hasText:/^Preview tools$/}).count(),1);assert.equal(await page.locator('.pxdt-nav').count(),1);assert.equal(await page.locator('.pxdt').count(),1);await page.locator('.pxdt [data-action=refresh]').click();await page.locator('.pxdt-nav').getByRole('button',{name:'Homeroom Heroes',exact:true}).click();await page.locator('.pxdt').waitFor({state:'hidden'});await page.screenshot({path:resolve(output,'persistent-devtools-after-navigation.png'),fullPage:true});return {originalMount:true,originalNavigation:true,originalPanel:true,readOnly:true};
 });
 await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'reduce'});mobile.setDefaultTimeout(8000);page=await mobile.newPage();
 page.on('console',m=>receipt.console.push({type:m.type(),text:m.text().slice(0,2000)}));page.on('pageerror',e=>receipt.console.push({type:'pageerror',text:String(e).slice(0,2000)}));page.on('request',r=>receipt.requests.push({url:r.url(),method:r.method(),resourceType:r.resourceType()}));
 await check('mobile-menu-navigation-and-width',async()=>{
  await open('/');await page.locator('#hh-public-nav-toggle').click();assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'true');await page.locator('#hh-mobile-nav').waitFor();await page.screenshot({path:resolve(output,'home-mobile-menu-expanded.png'),fullPage:true});
  await page.keyboard.press('Escape');assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('#hh-public-nav-toggle').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'true');
  await page.locator('#hh-mobile-nav a[data-public-route=contact]').click();await page.locator('#hh-contact-form').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);assert.equal(await page.locator('#hh-public-nav-toggle').getAttribute('aria-expanded'),'false');
  await fill(page.locator('#hh-contact-form'),'message','Independent 20 chars');assert.match(await page.locator('#hh-contact-counter').innerText(),/230/);assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);assert.equal(await page.locator('#hh-public-nav-toggle').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await page.screenshot({path:resolve(output,'contact-mobile-typed.png'),fullPage:true});
 });
 await check('embedded-mobile-controls-and-terms-focus',async()=>{
  await page.goto(process.env.HH_INTEGRATED_URL||`${config.preview}/#/hh/run`,{waitUntil:'networkidle',timeout:15000});const iframe=page.locator('iframe').first();await iframe.waitFor();const frame=page.frameLocator('iframe').first();await frame.locator('.hh-public-site').waitFor({timeout:10000});
  const bounds=await iframe.boundingBox();assert.ok(bounds?.width>300&&bounds.width<=390);await frame.locator('#hh-public-nav-toggle').click();await frame.locator('#hh-mobile-nav a[data-public-route=register]').click();await frame.locator('#hh-register-form').waitFor();
  const field=frame.locator('#hh-register-form [name=name]');await field.fill('Embedded Jordan');await frame.locator('#hh-terms-open').click();const dialog=frame.locator('[role=dialog]');await dialog.waitFor();assert.equal(await dialog.evaluate(e=>e.contains(e.ownerDocument.activeElement)),true);await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await field.inputValue(),'Embedded Jordan');
  const width=await frame.locator('html').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.ok(width.scroll<=width.width+1);await page.screenshot({path:resolve(output,'integrated-hh-mobile.png'),fullPage:true});return {iframe:bounds,innerDocument:width};
 });
 await mobile.close();
 const malformed=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});malformed.setDefaultTimeout(8000);await malformed.addInitScript(()=>sessionStorage.setItem('hh-forum-v1','{independent malformed storage'));page=await malformed.newPage();
 await check('forum-corrupt-storage-readable-recovery',async()=>{
  await open('/forum');assert.ok(await page.locator('.community-topic').count()>0);await text(/storage.*unavailable|unavailable.*storage|saved.*invalid/i);await previewRole('moderator');await previewControls();await page.locator('[data-event=forum-reset]').click();await previewRole('anonymous');assert.ok(await page.locator('.community-topic').count()>0);return {injectedFixture:'malformed local forum storage only; no auth/session injection'};
 });await malformed.close();
}finally{
 await browser.close();receipt.afterHashes=await pins();receipt.completedAt=new Date().toISOString();receipt.sourceStable=JSON.stringify(receipt.sourceHashes)===JSON.stringify(receipt.afterHashes);receipt.externalRuntimeRequests=receipt.requests.filter(r=>!r.url.startsWith('data:')&&!r.url.startsWith('blob:')&&new URL(r.url).origin!==new URL(leaf).origin);receipt.passed=receipt.sourceStable&&receipt.checks.every(c=>c.passed)&&!receipt.externalRuntimeRequests.length&&!receipt.console.some(c=>['error','pageerror'].includes(c.type));await writeFile(resolve(output,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({output,passed:receipt.passed,sourceStable:receipt.sourceStable,failures:receipt.checks.filter(c=>!c.passed).map(c=>c.name),consoleErrors:receipt.console.filter(c=>['error','pageerror'].includes(c.type)).length,externalRuntimeRequests:receipt.externalRuntimeRequests.length}));
}
process.exitCode=receipt.passed?0:1;
