import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../..'),product=resolve(process.env.CAPABILITY_PRODUCT_ROOT??process.argv[2]??join(root,'outputs/capability-lab')),evidence=resolve(process.env.CAPABILITY_EVIDENCE_ROOT??join(root,'outputs/capability-lab/evidence/independent'));
const cache=resolve(process.env.CAPABILITY_BROWSER_CACHE??join(root,'work/toolteam/browser')),{chromium}=await import(pathToFileURL(process.env.CAPABILITY_PLAYWRIGHT_MODULE??join(cache,'node_modules/playwright/index.mjs')));
const executable=process.env.CAPABILITY_CHROMIUM_PATH??join(cache,'browsers/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell'),libs=process.env.CAPABILITY_CHROMIUM_LIBS??['usr/lib/x86_64-linux-gnu','lib/x86_64-linux-gnu','usr/lib','lib'].map(p=>join(cache,'deps',p)).join(':');
const stamp=new Date().toISOString().replace(/[:.]/g,'-'),url=process.env.CAPABILITY_PREVIEW_URL??'http://127.0.0.1:4173',servicePid=Number(process.env.CAPABILITY_SERVICE_PID)||27734;
const report={schema:'capability-lab.independent.explain-browser.v1',generatedAt:new Date().toISOString(),product,url,checks:[],screenshots:[],errors:[],resources:[]};
const canon=v=>JSON.stringify(sort(v));function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
function near(a,b){assert.ok(Number.isFinite(a));assert.ok(Math.abs(a-b)<=1e-8+Math.abs(b)*1e-8,`${a} != ${b}`);}
async function hashes(){const names=['index.html','scripts/verify-all.mjs','scripts/verify-explain.mjs'];for(const folder of ['ui','src/explain','src/ml','src/watches','src/runtime','src/statistics','src/linalg','src/composed'])for(const n of await readdir(join(product,folder)))if(n.endsWith('.mjs')||n.endsWith('.css'))names.push(`${folder}/${n}`);return Promise.all(names.sort().map(async path=>{const b=await readFile(join(product,path));return{path,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')};}));}
async function check(name,action){try{const observed=await action();report.checks.push({name,status:'pass',...(observed?{observed}:{})});}catch(e){report.checks.push({name,status:'fail',error:e.message.slice(0,4500)});}}
await mkdir(evidence,{recursive:true});let browser,page;
const state=()=>page.evaluate(()=>window.explainLab.getState());
async function mode(name){await page.locator(`[data-workspace-mode="${name}"]`).click();}
async function shot(label,selector){const path=join(evidence,`explain-browser-${stamp}-${label}.png`);await page.locator(selector).screenshot({path});report.screenshots.push({label,path});}
async function predict(features,baseline='trainingMean',reference){await page.locator('#explain-input-json').fill(JSON.stringify(features));await page.locator('#explain-reference-select').selectOption(baseline);if(reference)await page.locator('#explain-reference-json').fill(JSON.stringify(reference));await page.locator('#explain-predict-button').click();return(await state()).explanation;}
async function draft(value){if(value)await page.locator('#explain-draft').fill(JSON.stringify(value));await page.locator('#explain-check-button').click();return(await state()).lastCheck;}
function lesson(algorithm){const patterns=algorithm==='kMeans'?[[0,0],[6,8]]:algorithm==='pca'?[[8,20],[10,19],[10,21],[12,20]]:[[0,0],[0,1],[1,0],[1,1]];return{schema:'ml-dataset.v1',sourceKind:'independent-browser-explanation-fixture',featureNames:['observableA','observableB'],...(algorithm==='linearRegression'||algorithm==='logisticRegression'?{targetName:'observedOutput'}:{}),records:Array.from({length:4},(_,g)=>patterns.map((features,i)=>({runId:`explain-run-${g}`,conditionId:`explain-condition-${g}`,features,...(algorithm==='linearRegression'?{target:5+3*features[0]-2*features[1]}:algorithm==='logisticRegression'?{target:Number(i>0)}:{})}))).flat()};}
async function fit(algorithm,settings={},standardize=false){await mode('ml');await page.locator('#ml-algorithm').selectOption(algorithm);await page.locator('#ml-training-input').fill(JSON.stringify(lesson(algorithm)));await page.locator('#ml-model-config').fill(JSON.stringify(settings));await page.locator('#ml-seed').fill('17');await page.locator('#ml-test-fraction').fill('0.25');await page.locator('#ml-standardize').setChecked(standardize);await page.locator('#ml-fit-button').click();const saved=await page.evaluate(()=>window.mlLab.getExperiment());assert.equal(saved.config.algorithm,algorithm);await mode('explain');await page.locator('#explain-model-select').selectOption('current');await page.locator('#explain-refresh-button').click();assert.equal(canon((await state()).experiment),canon(saved));return saved;}
async function watch(question,part='quartz.crystal'){await page.locator('#explain-watch-part').selectOption(part);await page.locator('#explain-watch-question').selectOption(question);await page.locator('#explain-watch-button').click();return(await state()).watchExplanation;}
function resources(label){const path=join(evidence,`explain-browser-resource-${stamp}-${label}.json`),r=JSON.parse(execFileSync('python3',[join(here,'preflight.py'),'--output',path,'--managed-pid',String(process.pid),'--managed-pid',String(servicePid)],{encoding:'utf8',timeout:10000,maxBuffer:250000}));assert.ok(r.managedObservation.belowBudgetAtSnapshot);report.resources.push({label,path,managedObservation:r.managedObservation});}
try{
  report.sourceFiles=await hashes();browser=await chromium.launch({headless:true,executablePath:executable,args:['--no-sandbox'],env:{...process.env,LD_LIBRARY_PATH:libs}});page=await browser.newPage({viewport:{width:1600,height:1100}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});assert.equal((await page.goto(url,{waitUntil:'networkidle'})).status(),200);await mode('explain');await page.waitForFunction(()=>window.explainLab?.getState);
  await check('configured service plus Explain Chromium resource snapshot',()=>resources('loaded'));
  await check('missing ML fit uses a clearly labeled actual synthetic demo',async()=>{assert.ok((await page.locator('#explain-source-badge').textContent()).includes('Synthetic demo fit'));const features=JSON.parse(await page.locator('#explain-input-json').inputValue()),result=await predict(features);assert.ok(Number.isFinite(result.prediction.predictions[0]));assert.equal(result.verification.matchesNativePrediction,true);assert.ok((await page.locator('.explain-hero').textContent()).includes('no live language-model provider'));return{sourceKind:(await state()).experiment.dataset.sourceKind,prediction:result.prediction};});
  await check('current trained/scaled linear model shows literal signed contributions and real input perturbation',async()=>{const saved=await fit('linearRegression',{},true),before=canon(saved),result=await predict([4,7],'custom',[1,3]);near(result.attribution.reference.prediction,2);near(result.prediction.predictions[0],3);near(result.attribution.contributions[0].contribution,9);near(result.attribution.contributions[1].contribution,-8);assert.equal(await page.locator('#explain-output .explain-bar-fill').count(),2);assert.equal(await page.locator('#explain-output .explain-bar-fill.negative').count(),1);assert.ok(!(await page.locator('#explain-output').textContent()).includes('[object Object]'));await page.locator('#explain-change-feature').selectOption('observableA');await page.locator('#explain-change-delta').fill('1');await page.locator('#explain-perturb-button').click();const changed=(await state()).perturbation;near(changed.originalPrediction.predictions[0],3);near(changed.changedPrediction.predictions[0],6);assert.equal(changed.modelUnchanged,true);assert.equal(changed.preprocessingRefit,false);assert.equal(canon(await page.evaluate(()=>window.mlLab.getExperiment())),before);assert.ok((await page.locator('#explain-perturb-output').textContent()).includes('6'));assert.ok((await page.locator('#explain-output').textContent()).includes(saved.dataset.targetName));await shot('linear-contributions','#explain-output');return{result,changed};});
  await check('actual claim controls accept evidence and reject value/unit/citation/prose/stale drafts',async()=>{await predict([4,7],'custom',[1,3]);await page.locator('#explain-prepare-draft').click();const valid=JSON.parse(await page.locator('#explain-draft').inputValue());assert.equal((await draft(valid)).accepted,true);const rejected=[];for(const mutate of [d=>{d.claims[0].value={predictions:[4]};},d=>{d.claims[0].unit='physical seconds';},d=>{d.claims[0].citationIds=['unrelated-manufacturer'];},d=>{d.text='All quartz watches were physically measured accurate to 0.0001 seconds.';}]){const bad=structuredClone(valid);mutate(bad);const r=await draft(bad);assert.equal(r.accepted,false);assert.equal(r.renderedText,'');rejected.push(r.errors);}await page.locator('#explain-stale-fixture').click();assert.equal((await draft()).accepted,false);await page.locator('#explain-input-json').fill('[5,7]');const changedInput=await draft(valid);assert.equal(changedInput.accepted,false);assert.ok(changedInput.errors.some(e=>e.code.includes('stale')));await predict([4,7],'custom',[1,3]);await page.locator('#explain-prepare-draft').click();assert.equal((await draft()).accepted,true);const panel=page.locator('#explain-evidence-sources').locator('..');if(await panel.getAttribute('open')===null)await panel.locator(':scope > summary').click();const active=(await state()).context,source=active.sources.find(s=>s.id==='fitted-model'),visible=await page.locator('#explain-evidence-sources').innerText();assert.equal(source.identity,active.modelIdentity);assert.ok(visible.includes(source.title));assert.ok(visible.includes(source.scope));for(const item of active.evidence){assert.ok(visible.includes(item.id));for(const id of item.citationIds)assert.ok(visible.includes(id));}for(const item of active.sources)assert.ok(visible.includes(item.id));assert.ok(visible.toLowerCase().includes('citation'));await shot('evidence-citations','#explain-evidence-sources');assert.ok((await page.locator('#explain-claim-results').textContent()).includes('fitted-model'));report.sourceInspector={contextId:active.contextId,source,visibleText:visible};await shot('checked-claims','#explain-claim-results');return{rejected,changedInput};});
  await check('classifier explanation sums logits and shows one sigmoid with actual changed probability',async()=>{await fit('logisticRegression',{learningRate:4,maxIterations:1,l2:0.25,threshold:0.9});const result=await predict([4,7],'custom',[1,3]);near(result.prediction.scores[0],12);near(result.prediction.probabilities[0],1/(1+Math.exp(-12)));near(result.attribution.reconstruction.reconstructedLogit,12);assert.ok((await page.locator('#explain-output').textContent()).toLowerCase().includes('logit'));assert.ok((await page.locator('#explain-output').textContent()).toLowerCase().includes('probability'));await page.locator('#explain-change-feature').selectOption('observableA');await page.locator('#explain-change-delta').fill('1');await page.locator('#explain-perturb-button').click();const changed=(await state()).perturbation;near(changed.changedPrediction.scores[0],13);near(changed.changedPrediction.probabilities[0],1/(1+Math.exp(-13)));await shot('logistic','#explain-output');return{result,changed};});
  await check('cluster and PCA controls display real squared terms and retained centered scores',async()=>{await fit('kMeans',{k:2,maxIterations:10});const cluster=await predict([3,4]);near(cluster.prediction.squaredDistances[0],25);near(cluster.prediction.distances[0],5);assert.equal(cluster.prediction.assignments[0],0);assert.ok((await page.locator('#explain-output').textContent()).includes('units²'));await shot('cluster','#explain-output');await fit('pca',{components:1});const pca=await predict([14,20]);near(pca.prediction.projected[0][0],4);assert.equal(pca.attribution.components.length,1);assert.ok((await page.locator('#explain-output').textContent()).includes('Component 1'));assert.ok(!(await page.locator('#explain-output').textContent()).includes('Component 2'));await shot('pca','#explain-output');return{cluster,pca};});
  await check('Watches controls preserve actual state under explosion and focused selection',async()=>{await mode('watches');await page.locator('#watch-reset').click();await page.locator('#watch-step-event').selectOption('mechanicalBeat');await page.locator('#watch-step').click();const before=await page.evaluate(()=>window.watchLab.getState());assert.equal(before.counters.mechanicalBeats,1);assert.equal(before.counters.quartzCycles,4096);await page.locator('#watch-explode').focus();await page.keyboard.press('End');assert.ok((await page.locator('#watch-explode-value').textContent()).includes('100'));const part=page.locator('.watch-model-svg [data-part-id="quartz.crystal"]');await part.focus();await page.keyboard.press('Space');assert.equal(canon(await page.evaluate(()=>window.watchLab.getState())),canon(before));await mode('explain');await page.locator('#explain-refresh-button').click();const tick=await watch('tick-boundary','mechanical.escapeWheel');assert.equal(tick.question.event.event,'mechanicalBeat');const view=await watch('view-invariance','quartz.rotor');assert.equal(view.question.stateUnchanged,true);assert.equal(view.question.geometryChanged,true);assert.equal(canon(await page.evaluate(()=>window.watchLab.getState())),canon(before));return{tick,view};});
  await check('watch questions inspect current power/timing/divider/source evidence and stale state fails',async()=>{await mode('watches');await page.locator('#watch-step-event').selectOption('motorCommand');await page.locator('#watch-step').click();await mode('explain');await page.locator('#explain-refresh-button').click();const divider=await watch('divider');assert.equal(divider.question.referenceCycleCount,32768);assert.equal(divider.question.lastStage.outputCount,1);const gear=await watch('gear-ratio','quartz.gears');assert.ok(gear.question.trains.quartz);const energy=await watch('energy-path','quartz.battery');assert.equal(energy.question.quartz.available,true);await page.locator('#explain-prepare-draft').click();const oldDraft=JSON.parse(await page.locator('#explain-draft').inputValue());assert.equal((await draft(oldDraft)).accepted,true);await mode('watches');await page.locator('#watch-energy-battery').uncheck();const off=await page.evaluate(()=>window.watchLab.getState());await page.locator('#watch-duration-numerator').fill('1');await page.locator('#watch-duration-denominator').fill('1');await page.locator('#watch-advance').click();const later=await page.evaluate(()=>window.watchLab.getState());assert.equal(later.counters.quartzCycles,off.counters.quartzCycles);await mode('explain');const rejected=await draft(oldDraft);assert.equal(rejected.accepted,false);const now=await watch('energy-path','quartz.battery');assert.equal(now.question.quartz.available,false);const timing=await watch('timing-path','quartz.crystal');assert.equal(timing.question.quartz.timing.available,false);const context=(await state()).watchContext,links=await page.locator('#explain-evidence-sources a').evaluateAll(nodes=>nodes.map(n=>n.href));assert.ok(context.sources.filter(s=>s.url).every(s=>links.includes(s.url)));const unsupported=await watch('physical-accuracy');assert.equal(unsupported.supported,false);assert.ok(/measur|friction|temperature|physical/i.test(await page.locator('#explain-watch-output').textContent()));assert.equal((await watch('unsupported-question')).supported,false);await watch('energy-path','quartz.battery');await shot('watch-power-source','#explain-watch-output');return{divider,gear,now,timing,rejected,unsupported};});
  await check('Foundations still execute edited mathematics with real graph and trace',async()=>{await mode('foundations');await page.locator('#capability-select').selectOption('statistics.mean');await page.locator('#input-editor').fill('{"values":[1,3]}');await page.locator('#run-button').click();assert.ok((await page.locator('#result').textContent()).includes('2'));await page.locator('#input-editor').fill('{"values":[3,5]}');await page.locator('#run-button').click();assert.ok((await page.locator('#result').textContent()).includes('4'));assert.ok((await page.locator('#execution-trace').textContent()).includes('statistics.mean'));assert.ok(await page.locator('#dependency-graph').count());await mode('explain');assert.ok(await page.locator('#explain-predict-button').count());});
  await check('complete four-track browser source pin map stayed unchanged',async()=>assert.equal(canon(await hashes()),canon(report.sourceFiles)));
  await check('resource snapshot after all tracks and explanation checks',()=>resources('exercised'));
  await check('no console/page errors in four-track interactions',()=>assert.deepEqual(report.errors,[]));
}catch(e){report.checks.push({name:'Explain browser registration',status:'fail',error:e.message.slice(0,4500)});}finally{await browser?.close();}
report.summary={pass:report.checks.filter(c=>c.status==='pass').length,fail:report.checks.filter(c=>c.status==='fail').length,resourceSnapshotsOnly:true,osHardLimitEstablished:false};await writeFile(join(evidence,`explain-browser-${stamp}.json`),JSON.stringify(report,null,2)+'\n');await writeFile(join(evidence,'explain-browser-latest.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({summary:report.summary,failures:report.checks.filter(c=>c.status==='fail'),screenshots:report.screenshots,receipt:join(evidence,'explain-browser-latest.json')},null,2));process.exitCode=report.summary.fail?1:0;
