import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../..');
const product=resolve(process.env.CAPABILITY_PRODUCT_ROOT??process.argv[2]??join(root,'outputs/capability-lab'));
const evidence=resolve(process.env.CAPABILITY_EVIDENCE_ROOT??join(root,'outputs/capability-lab/evidence/independent'));
const f=JSON.parse(await readFile(join(here,'explain-fixtures.json'),'utf8'));
const report={schema:'capability-lab.independent.explain-gate.v1',generatedAt:new Date().toISOString(),product,fixtureProvenance:f.provenance,checks:[],pending:[],sourceFiles:[]};
const clone=v=>structuredClone(v);
function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function sorted(v){return Array.isArray(v)?v.map(sorted):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sorted(v[k])])):v;}
const canonical=v=>JSON.stringify(sorted(v));
function near(a,b,t=1e-9){if(Array.isArray(b)){assert.equal(a.length,b.length);b.forEach((x,i)=>near(a[i],x,t));}else{assert.ok(Number.isFinite(a));assert.ok(Math.abs(a-b)<=t+t*Math.abs(b),`${a} != ${b}`);}}
async function check(name,family,action){try{const observed=await action();report.checks.push({name,family,status:'pass',...(observed?{observed}:{})});}catch(error){report.checks.push({name,family,status:'fail',error:error.message.slice(0,5000)});}}
async function snapshot(){const result=[];for(const family of ['explain','ml','watches']){let names=[];try{names=await readdir(join(product,'src',family));}catch{}for(const name of names.filter(n=>n.endsWith('.mjs')).sort()){const path=`src/${family}/${name}`,bytes=await readFile(join(product,path));result.push({path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}}return result;}
const modules={};report.sourceFiles=await snapshot();
await Promise.all(['regression','classification','clustering','pca','grounding','watch','index'].map(async name=>{try{modules[name]=await import(pathToFileURL(join(product,`src/explain/${name}.mjs`)));}catch(error){report.pending.push({module:name,error:error.message});}}));
const ml=await import(pathToFileURL(join(product,'src/ml/index.mjs'))),watches=await import(pathToFileURL(join(product,'src/watches/index.mjs')));
function dataset(names,patterns,target){return{schema:'ml-dataset.v1',sourceKind:'independent-explanation-fixture',featureNames:names,...(target?{targetName:'observedOutput'}:{}),records:Array.from({length:4},(_,group)=>patterns.map((features,i)=>({runId:`literal-run-${group}`,conditionId:`literal-condition-${group}`,features:[...features],...(target?{target:target(features,i)}:{})}))).flat()};}
function fit(data,algorithm='linearRegression',standardize=false,modelConfig={},featureNames){return ml.runMLExperiment({dataset:data,algorithm,standardize,modelConfig,featureNames:featureNames??data.featureNames,seed:17,testFraction:0.25});}
const rawData=dataset(['observableA','observableB'],[[0,0],[0,1],[1,0],[1,1]],x=>5+3*x[0]-2*x[1]);
const raw=fit(rawData),selectedData=dataset(f.selectedStandardized.sourceFeatureNames,[[100,8,15],[200,8,25],[300,12,15],[400,12,25]],x=>-2+1.5*x[1]-0.4*x[2]);
const scaled=fit(selectedData,'linearRegression',true,{},['observableA','observableB']);
const actualPrediction=(experiment,features)=>ml.predictMLModel({experiment,records:[{runId:'new-observation',conditionId:'new-observation',features:[...features]}]});

if(modules.regression){const reg=modules.regression;
  await check('literal baseline plus raw contributions reconstruct the real linear prediction','linear-attribution',()=>{const before=canonical(raw),result=reg.explainLinearRegression(freeze({experiment:clone(raw),features:clone(f.linear.features),baseline:clone(f.linear.baseline)}));near(result.reference.prediction,2);near(result.contributions.map(c=>c.coefficient),[3,-2]);near(result.contributions.map(c=>c.contribution),[9,-8]);near(result.prediction,3);near(result.reconstructedPrediction,3);assert.ok(result.roundoff.withinTolerance);assert.ok(result.roundoff.tolerance<=1e-9);near(actualPrediction(raw,f.linear.features).predictions,[3]);assert.equal(canonical(raw),before);return result;});
  await check('retained selected indices and scaler yield original-unit contributions','retained-preprocessing',()=>{const s=f.selectedStandardized,result=reg.explainLinearRegression({experiment:scaled,features:s.features});near(scaled.preprocessing.means,s.means);near(scaled.preprocessing.scales,s.scales);assert.deepEqual(result.contributions.map(c=>c.index),[1,2]);near(result.reference.featureValues,s.means);near(result.reference.prediction,5);near(result.contributions.map(c=>c.coefficient),s.rawCoefficients);near(result.contributions.map(c=>c.contribution),s.trainingMeanContributions);near(result.prediction,7);near(actualPrediction(scaled,s.features).predictions,[7]);const zero=reg.explainLinearRegression({experiment:scaled,features:s.features,baseline:'zero'});near(zero.reference.prediction,-2);near(zero.contributions.map(c=>c.contribution),[21,-12]);const explicit=reg.explainLinearRegression({experiment:scaled,features:s.features,baseline:[-999,10,20]});near(explicit.reference.prediction,5);near(explicit.prediction,7);return{trainingMean:result,zero,explicit};});
  await check('named raw-unit deltas change the real prediction without refitting','controlled-perturbation',()=>{const before=canonical(scaled),changed=reg.perturbLinearRegression(freeze({experiment:clone(scaled),features:clone(f.selectedStandardized.features),changes:{observableA:2}}));near(changed.originalPrediction,7);near(changed.changedPrediction,10);near(changed.changedFeatures,[999,16,30]);near(changed.predictionDelta,3);assert.equal(changed.modelUnchanged,true);assert.equal(changed.preprocessingRefit,false);const unused=reg.perturbLinearRegression({experiment:scaled,features:f.selectedStandardized.features,changes:{unusedObservable:1000}});near(unused.predictionDelta,0);assert.equal(canonical(scaled),before);return{changed,unused};});
  await check('reference means use retained training rows and outputs have no live aliases','artifact-integrity',()=>{const original=reg.explainLinearRegression({experiment:raw,features:f.linear.features}),changedData=clone(rawData);raw.split.testIndices.forEach(i=>{changedData.records[i].features=[1000,-1000];changedData.records[i].target=99999;});const edited=fit(changedData),after=reg.explainLinearRegression({experiment:edited,features:f.linear.features});near(after.reference.featureValues,original.reference.featureValues);near(after.reference.prediction,original.reference.prediction);const before=canonical(raw),returned=reg.explainLinearRegression({experiment:raw,features:f.linear.features});returned.contributions[0].contribution=999;returned.sourceIdentity.dataFingerprint.hash='poisoned';assert.equal(canonical(raw),before);assert.equal(canonical(reg.explainLinearRegression({experiment:raw,features:f.linear.features})),canonical(original));assert.throws(()=>reg.perturbLinearRegression({experiment:raw,features:f.linear.features,changes:{missing:1}}));assert.throws(()=>reg.explainLinearRegression({experiment:scaled,features:[14,30]}));const forged=clone(raw);forged.dataset.records[0].features[0]+=1;assert.throws(()=>reg.explainLinearRegression({experiment:forged,features:f.linear.features}),/fingerprint|identity/i);});
}

if(modules.classification){await check('trained logistic contributions reconstruct logit and apply sigmoid exactly once','logistic-attribution',()=>{const experiment=fit(dataset(['observableA','observableB'],[[0,0],[0,1],[1,0],[1,1]],(x,i)=>Number(i>0)),'logisticRegression',false,{learningRate:4,maxIterations:1,tolerance:0,l2:0.25,threshold:0.9}),before=canonical(experiment);near(experiment.model.coefficients,[1,1]);near(experiment.model.intercept,1);const result=modules.classification.explainLogisticRegression(freeze({experiment:clone(experiment),features:[4,7],baseline:[1,3]}));near(result.baseline.logit,5);near(result.contributions.map(c=>c.logitContribution),[3,4]);near(result.prediction.logit,12);near(result.reconstruction.reconstructedLogit,12);assert.ok(result.reconstruction.withinTolerance);near(result.prediction.probability,1/(1+Math.exp(-12)));assert.equal(result.prediction.label,1);assert.ok(Math.abs(result.prediction.probability-(result.baseline.probability+7))>1);const changed=modules.classification.perturbLogisticRegression({experiment,features:[4,7],changes:{observableA:5},baseline:[1,3]});near(changed.after.logit,13);near(changed.after.probability,1/(1+Math.exp(-13)));near(actualPrediction(experiment,[5,7]).scores,[13]);assert.equal(canonical(experiment),before);return{result,changed};});}
if(modules.clustering){await check('cluster coordinate squares reconstruct squared distance rather than norm','cluster-attribution',()=>{const experiment=fit(dataset(['observableA','observableB'],[[0,0],[6,8]]),'kMeans',false,{k:2,maxIterations:10,tolerance:0}),before=canonical(experiment),result=modules.clustering.explainKMeans(freeze({experiment:clone(experiment),features:[3,4]}));assert.equal(result.prediction.clusterIndex,0);assert.equal(result.prediction.tieBreak,'lowest-index');assert.equal(result.prediction.exactDistanceTie,true);near(result.centers.map(c=>c.selectedCoordinates.map(v=>v.squaredContribution)),[[9,16],[9,16]]);near(result.centers.map(c=>c.squaredDistance),[25,25]);near(result.centers.map(c=>c.distance),[5,5]);near(actualPrediction(experiment,[3,4]).squaredDistances,[25]);const changed=modules.clustering.explainKMeans({experiment,features:[0,4]});near(changed.centers.map(c=>c.squaredDistance).sort((a,b)=>a-b),[16,52]);assert.equal(canonical(experiment),before);return{result,changed};});}
if(modules.pca){await check('PCA loading terms use fitted training centering and real directions','pca-attribution',()=>{const experiment=fit(dataset(['observableA','observableB'],[[8,20],[10,19],[10,21],[12,20]]),'pca',false,{components:2}),before=canonical(experiment),result=modules.pca.explainPCA(freeze({experiment:clone(experiment),features:[14,20]}));near(experiment.model.means,[10,20]);near(result.components.map(c=>c.score),[4,0]);near(result.components.map(c=>c.contributions.map(v=>v.contribution)),[[4,0],[0,0]]);near(result.components.map(c=>c.explainedVarianceRatio),[0.8,0.2]);assert.ok(result.components.every(c=>c.reconstruction.withinTolerance));assert.ok(result.trace.calls.some(c=>c.operationId==='linalg.dot'));near(actualPrediction(experiment,[14,20]).projected,[[4,0]]);assert.equal(canonical(experiment),before);return result;});}

if(modules.grounding){const g=modules.grounding,sources=watches.componentSources();
  const input={contextId:'literal-context',stateIdentity:'literal-state',modelIdentity:'literal-model',sourceKind:'model-derived',sources:[{id:'fitted-model',title:'Retained mathematical model',scope:'model parameters',identity:'literal-model',url:null},{id:'dataset-lineage',title:'Declared mathematical fixture',scope:'data identity',identity:'literal-state',url:null}],evidence:[{id:'literal-prediction',value:3,unit:'model output units',kind:'derived',permittedScopes:['model.prediction'],citationIds:['fitted-model']}]};
  let context;await check('typed matching numerical claim renders only its evidence','claim-grounding',()=>{context=g.buildEvidenceContext(freeze(clone(input)));const item=context.evidence[0],draft={contextId:context.contextId,stateIdentity:context.stateIdentity,modelIdentity:context.modelIdentity,claims:[{evidenceId:item.id,value:item.value,unit:item.unit,kind:item.kind,scope:'model.prediction',citationIds:item.citationIds}]},result=g.checkExplanationClaims({context,draft});assert.equal(result.accepted,true);assert.ok(result.renderedText.includes('3'));assert.equal(canonical(g.checkExplanationClaims({context,draft})),canonical(result));report.validDraft=draft;return result;});
  if(context){const valid=report.validDraft,reject=draft=>{const result=g.checkExplanationClaims({context,draft});assert.equal(result.accepted,false);assert.equal(result.renderedText,'');assert.deepEqual(result.claims,[]);assert.ok(result.errors.every(e=>e.code&&e.message));return result;};
    for(const [label,mutate] of [['wrong-value',d=>{d.claims[0].value=4;}],['wrong-unit',d=>{d.claims[0].unit='physical seconds';}],['unknown-evidence',d=>{d.claims[0].evidenceId='unknown';}],['wrong-citation',d=>{d.claims[0].citationIds=['dataset-lineage'];}],['missing-citation',d=>{d.claims[0].citationIds=[];}],['unsupported-scope',d=>{d.claims[0].scope='physical.causation';}],['wrong-kind',d=>{d.claims[0].kind='measurement';}],['stale-context',d=>{d.contextId='old';}],['stale-state',d=>{d.stateIdentity='old';}],['stale-model',d=>{d.modelIdentity='old';}],['provider-prose-bypass',d=>{d.text='Every quartz watch was physically measured accurate to 0.0001 seconds.';}]])await check(`checker rejects ${label}`,'claim-rejection',()=>{const draft=clone(valid);mutate(draft);return reject(draft);});
    await check('caller-declared physical source kind never establishes instrument provenance','provenance-limits',()=>{const physical=g.buildEvidenceContext({...clone(input),sourceKind:'physical-measured'});const result=g.checkExplanationClaims({context:physical,draft:clone(valid)});assert.equal(result.accepted,false);assert.ok(result.errors.some(e=>e.code==='unverified-physical-provenance'));return result;});
    await check('bounded context/draft traversal rejects cycles, depth, sparse arrays and oversized values','context-bounds',()=>{for(const candidate of ['cycle','depth','size']){const forged=clone(context);if(candidate==='cycle')forged.extra=forged;if(candidate==='depth'){let value=0;for(let i=0;i<70;i++)value={next:value};forged.extra=value;}if(candidate==='size')forged.extra='x'.repeat(1000001);const result=g.checkExplanationClaims({context:forged,draft:valid});assert.equal(result.accepted,false);}const cyclic=clone(valid);cyclic.extra=cyclic;assert.equal(g.checkExplanationClaims({context,draft:cyclic}).accepted,false);const sparse=clone(valid);sparse.claims=Array(1);assert.equal(g.checkExplanationClaims({context,draft:sparse}).accepted,false);assert.equal(g.checkExplanationClaims({context,draft:{...clone(valid),claims:Array.from({length:65},()=>clone(valid.claims[0]))}}).accepted,false);});
  }
  await check('curated citations cannot launder universal quartz or physical measurement text','curated-fact-safety',()=>{const source=sources.find(s=>s.id==='grand-seiko-quartz');for(const value of ['Every quartz watch uses exactly 32768 Hz and physically pulses once per second with measured accuracy of 0.0001 seconds.','This schematic proves temperature and friction cannot affect any real watch.']){const bad={contextId:'fabricated-fact',stateIdentity:'fixture-state',modelIdentity:'fixture-model',sourceKind:'curated-source',sources:[source],evidence:[{id:'invented-universal',value,unit:'source note',kind:'fact',permittedScopes:['source.mechanismFact'],citationIds:[source.id]}]};let rejected=false;try{const c=g.buildEvidenceContext(bad),e=c.evidence[0],result=g.checkExplanationClaims({context:c,draft:{contextId:c.contextId,stateIdentity:c.stateIdentity,modelIdentity:c.modelIdentity,claims:[{evidenceId:e.id,value:e.value,unit:e.unit,kind:e.kind,scope:'source.mechanismFact',citationIds:e.citationIds}]}});rejected=result.accepted===false;}catch{rejected=true;}assert.ok(rejected,`fabricated fact was blessed: ${value}`);}const wrongSource={...source,url:'https://example.invalid/fake'};assert.throws(()=>g.buildEvidenceContext({contextId:'bad-source',stateIdentity:'s',modelIdentity:'m',sourceKind:'curated-source',sources:[wrongSource],evidence:[{id:'s',value:source.supports,unit:'source note',kind:'fact',permittedScopes:['source.mechanismFact'],citationIds:[source.id]}]}));});
}

if(modules.index){const api=modules.index,draftFor=context=>({contextId:context.contextId,stateIdentity:context.stateIdentity,modelIdentity:context.modelIdentity,claims:context.evidence.map(e=>({evidenceId:e.id,value:clone(e.value),unit:e.unit,kind:e.kind,scope:e.permittedScopes[0],citationIds:clone(e.citationIds)}))});
  await check('retrieval wrapper preserves actual predictions and checked claims for all four models','public-composition',()=>{const examples=[{experiment:scaled,features:f.selectedStandardized.features},{experiment:fit(dataset(['observableA','observableB'],[[0,0],[0,1],[1,0],[1,1]],(x,i)=>Number(i>0)),'logisticRegression',false,{learningRate:4,maxIterations:1,l2:0.25}),features:[4,7]},{experiment:fit(dataset(['observableA','observableB'],[[0,0],[6,8]]),'kMeans',false,{k:2,maxIterations:10}),features:[3,4]},{experiment:fit(dataset(['observableA','observableB'],[[8,20],[10,19],[10,21],[12,20]]),'pca',false,{components:2}),features:[14,20]}],results=[];for(const input of examples){const before=canonical(input),result=api.explainPrediction(freeze(clone(input)));assert.equal(canonical(result.prediction),canonical(actualPrediction(input.experiment,input.features)));assert.equal(result.verification.matchesNativePrediction,true);assert.ok(result.calculationTrace.calls.some(c=>c.id==='src/ml/index.mjs#predictMLModel'));assert.ok(result.calculationTrace.bytes<=api.explanationLimits.maxTraceBytes);const checked=api.checkExplanationClaims({context:result.context,draft:draftFor(result.context),current:input});assert.equal(checked.accepted,true);assert.equal(canonical(input),before);assert.equal(canonical(api.explainPrediction(clone(input))),canonical(result));results.push({algorithm:result.algorithm,verification:result.verification,context:result.context,checked});}return{results};});
  await check('public perturbation uses raw deltas with unchanged selected parameters','public-perturbation',()=>{const input={experiment:scaled,features:f.selectedStandardized.features,changes:{observableA:2}},before=canonical(scaled),result=api.perturbPrediction(freeze(clone(input)));near(result.originalPrediction.predictions,[7]);near(result.changedPrediction.predictions,[10]);near(result.changedFeatures,[999,16,30]);assert.equal(result.modelUnchanged,true);assert.equal(result.preprocessingRefit,false);assert.equal(result.originalAttribution.contributions[0].coefficient,result.changedAttribution.contributions[0].coefficient);assert.equal(api.checkExplanationClaims({context:result.context,draft:draftFor(result.context),current:input}).accepted,true);const unused=api.perturbPrediction({experiment:scaled,features:f.selectedStandardized.features,changes:{unusedObservable:1000}});near(unused.predictionDelta,0);assert.equal(canonical(scaled),before);return result;});
  await check('checker regenerates real evidence and rejects stale input/model/data or forged context','retrieval-identity',()=>{const input={experiment:scaled,features:f.selectedStandardized.features},result=api.explainPrediction(input),draft=draftFor(result.context);assert.equal(api.checkExplanationClaims({context:result.context,draft}).accepted,true);const changedInput={...input,features:[999,16,30]};assert.equal(api.checkExplanationClaims({context:result.context,draft,current:changedInput}).accepted,false);const changedModel=clone(scaled);changedModel.model.coefficients[0]+=1;assert.equal(api.checkExplanationClaims({context:result.context,draft,current:{...input,experiment:changedModel}}).accepted,false);const changedData=clone(scaled);changedData.dataset.records[0].target+=1;assert.equal(api.checkExplanationClaims({context:result.context,draft,current:{...input,experiment:changedData}}).accepted,false);const forged=clone(result.context);forged.evidence[0].value={predictions:[9999]};const forgedDraft=draftFor(forged);assert.equal(api.checkExplanationClaims({context:forged,draft:forgedDraft,current:input}).accepted,false);const prose={...clone(draft),text:'I physically measured every watch and proved universal accuracy.'};assert.equal(api.checkExplanationClaims({context:result.context,draft:prose,current:input}).accepted,false);});
}
if(modules.watch){const ask=(state,questionId,componentId)=>modules.watch.explainWatch({state,questionId,...(componentId?{componentId}:{})});
  await check('watch selected step explanation follows the retained selected event, not range append order','watch-tick-selection',()=>{let mechanical=watches.createWatchRun();mechanical=watches.applyWatchAction(mechanical,{type:'step',event:'quartzCycle'});mechanical=watches.applyWatchAction(mechanical,{type:'step',event:'mechanicalBeat'});assert.deepEqual(mechanical.counters,f.watch.fractionalCounters);const beat=ask(mechanical,'tick-boundary','mechanical.escapeWheel');assert.equal(beat.question.event.event,'mechanicalBeat');let quartz=watches.createWatchRun();quartz=watches.applyWatchAction(quartz,{type:'step',event:'motorCommand'});assert.deepEqual(quartz.counters,f.watch.oneSecondCounters);const motor=ask(quartz,'tick-boundary','quartz.rotor');assert.equal(motor.question.event.event,'motorCommand');return{beat,motor};});
  await check('watch explanations bind actual energy, live versus nominal rates, divider and view invariance','watch-evidence',()=>{let state=watches.createWatchRun();state=watches.applyWatchAction(state,{type:'step',event:'motorCommand'});const before=canonical(state),divider=ask(state,'divider');assert.equal(divider.question.stageCount,15);assert.equal(divider.question.referenceCycleCount,32768);assert.equal(divider.question.lastStage.outputCount,1);const energy=ask(state,'energy-path');assert.equal(energy.question.mechanical.available,true);assert.equal(energy.question.quartz.available,true);const view=ask(state,'view-invariance','quartz.rotor');assert.equal(view.question.stateUnchanged,true);assert.equal(view.question.geometryChanged,true);assert.equal(view.question.beforeIdentity,view.question.afterIdentity);assert.deepEqual(view.question.countersBefore,view.question.countersAfter);assert.ok(view.calculationTrace.calls.filter(c=>c.id?.includes('watchGeometry')).length>=2);assert.equal(canonical(state),before);state=watches.applyWatchAction(state,{type:'rate',model:'quartz',hz:16384});const rates=ask(state,'current-vs-nominal-rate');assert.deepEqual(rates.question.quartz.currentHz,{numerator:16384,denominator:1});assert.deepEqual(rates.question.quartz.nominalHz,{numerator:32768,denominator:1});state=watches.applyWatchAction(state,{type:'energy',source:'battery',enabled:false});const off=ask(state,'energy-path');assert.equal(off.question.quartz.available,false);const unsupported=ask(state,'physical-accuracy');assert.equal(unsupported.supported,false);assert.ok(/physical|measur|temperature|friction/i.test(unsupported.limitation));assert.equal(ask(state,'invented-temperature-compensation').supported,false);return{divider,energy,view,rates,off,unsupported};});
  await check('watch explanation rejects tampered state, model counters, retained history and oversized input','watch-state-validation',()=>{let state=watches.createWatchRun();state=watches.applyWatchAction(state,{type:'step',event:'motorCommand'});for(const mutate of [s=>{s.counters.quartzCycles+=1;},s=>{s.models.quartz.counts.referenceCycles+=1;},s=>{s.rates.quartz={numerator:-1,denominator:1};},s=>{s.history.events[0].end+=1;},s=>{s.history.bytes=0;},s=>{s.extra=s;},s=>{let v=0;for(let i=0;i<80;i++)v={next:v};s.extra=v;},s=>{s.extra='x'.repeat(1048577);}]){const forged=clone(state);mutate(forged);assert.throws(()=>ask(forged,'divider'));}});
}
await check('all required Explain modules are loadable','public-API',()=>assert.deepEqual(report.pending,[]));
await check('source bytes stayed unchanged during Explain gate','source-provenance',async()=>assert.equal(canonical(await snapshot()),canonical(report.sourceFiles)));
report.summary={pass:report.checks.filter(c=>c.status==='pass').length,fail:report.checks.filter(c=>c.status==='fail').length,blocked:report.pending.length>0,families:[...new Set(report.checks.map(c=>c.family))]};
await mkdir(evidence,{recursive:true});const stamp=report.generatedAt.replace(/[:.]/g,'-');await writeFile(join(evidence,`explain-gate-${stamp}.json`),JSON.stringify(report,null,2)+'\n');await writeFile(join(evidence,'explain-gate-latest.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({summary:report.summary,pending:report.pending,failures:report.checks.filter(c=>c.status==='fail'),receipt:join(evidence,'explain-gate-latest.json')},null,2));process.exitCode=report.summary.fail||report.summary.blocked?1:0;
