import {mkdir,writeFile,readFile,readdir} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';

const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../..'),product=resolve(process.env.CAPABILITY_PRODUCT_ROOT??process.argv[2]??join(root,'outputs/capability-lab')),evidence=resolve(process.env.CAPABILITY_EVIDENCE_ROOT??join(root,'outputs/capability-lab/evidence/independent'));
const cache=resolve(process.env.CAPABILITY_BROWSER_CACHE??join(root,'work/toolteam/browser')),{chromium}=await import(pathToFileURL(process.env.CAPABILITY_PLAYWRIGHT_MODULE??join(cache,'node_modules/playwright/index.mjs')));
const executable=process.env.CAPABILITY_CHROMIUM_PATH??join(cache,'browsers/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell'),libraries=process.env.CAPABILITY_CHROMIUM_LIBS??['usr/lib/x86_64-linux-gnu','lib/x86_64-linux-gnu','usr/lib','lib'].map(p=>join(cache,'deps',p)).join(':');
const fixtures=JSON.parse(await readFile(join(here,'ml-fixtures.json'),'utf8')),stamp=new Date().toISOString().replace(/[:.]/g,'-'),url=process.env.CAPABILITY_PREVIEW_URL??'http://127.0.0.1:4173',servicePid=Number(process.env.CAPABILITY_SERVICE_PID)||27734;
const report={schema:'capability-lab.independent.ml-browser.v1',generatedAt:new Date().toISOString(),product,url,checks:[],screenshots:[],errors:[],resources:[]};
const canonical=v=>JSON.stringify(sort(v));function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
function near(a,b){if(Array.isArray(b)){assert.equal(a.length,b.length);b.forEach((v,i)=>near(a[i],v));}else{assert.ok(Number.isFinite(a));assert.ok(Math.abs(a-b)<=1e-7+Math.abs(b)*1e-7,`${a} != ${b}`);}}
async function fingerprints(){const names=['index.html','ui/app.mjs','ui/style.css','ui/ml.mjs',...(await readdir(join(product,'src/ml'))).filter(n=>n.endsWith('.mjs')).map(n=>`src/ml/${n}`)];return Promise.all(names.sort().map(async path=>{const bytes=await readFile(join(product,path));return{path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}));}
async function check(name,action){try{const observed=await action();report.checks.push({name,status:'pass',...(observed?{observed}:{})});}catch(error){report.checks.push({name,status:'fail',error:error.message.slice(0,3500)});}}
await mkdir(evidence,{recursive:true});let browser,page;
const experiment=()=>page.evaluate(()=>window.mlLab.getExperiment());
async function screenshot(label){await page.locator('#ml-fit-button').scrollIntoViewIfNeeded();const path=join(evidence,`ml-browser-${stamp}-${label}.png`);await page.screenshot({path,fullPage:false});report.screenshots.push({label,path});const plotPath=join(evidence,`ml-browser-${stamp}-${label}-plot.png`);await page.locator('#ml-plot-wrap').screenshot({path:plotPath});report.screenshots.push({label:`${label}-plot`,path:plotPath});}
async function fit(dataset,algorithm='linearRegression',settings={}){
  await page.locator('#ml-algorithm').selectOption(algorithm);await page.locator('#ml-training-input').fill(JSON.stringify(dataset,null,2));
  await page.locator('#ml-group-by').selectOption('conditionId');await page.locator('#ml-test-fraction').fill('0.25');await page.locator('#ml-seed').fill('17');await page.locator('#ml-model-config').fill(JSON.stringify(settings));
  const before=await page.evaluate(()=>window.__mlEvents.filter(e=>e.kind==='fit').length);await page.locator('#ml-fit-button').click();
  await page.waitForFunction(n=>window.__mlEvents.filter(e=>e.kind==='fit').length>n,before,{timeout:5000});return experiment();
}
async function predict(records,evaluate=false){await page.locator('#ml-prediction-input').fill(JSON.stringify(records,null,2));const kind=evaluate?'evaluate':'predict',before=await page.evaluate(kind=>window.__mlEvents.filter(e=>e.kind===kind).length,kind);await page.locator(evaluate?'#ml-evaluate-button':'#ml-predict-button').click();await page.waitForFunction(({kind,before})=>window.__mlEvents.filter(e=>e.kind===kind).length>before,{kind,before},{timeout:5000});return page.evaluate(kind=>window.__mlEvents.filter(e=>e.kind===kind).at(-1).detail.result,kind);}
function resources(label){const path=join(evidence,`ml-browser-resource-${stamp}-${label}.json`),result=JSON.parse(execFileSync('python3',[join(here,'preflight.py'),'--output',path,'--managed-pid',String(process.pid),'--managed-pid',String(servicePid)],{encoding:'utf8',timeout:10000,maxBuffer:250000}));assert.ok(result.managedObservation.belowBudgetAtSnapshot);report.resources.push({label,path,managedObservation:result.managedObservation});}
try{
  browser=await chromium.launch({headless:true,executablePath:executable,args:['--no-sandbox'],env:{...process.env,LD_LIBRARY_PATH:libraries}});page=await browser.newPage({viewport:{width:1600,height:1100},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
  const response=await page.goto(url,{waitUntil:'networkidle'});assert.equal(response.status(),200);await page.locator('[data-workspace-mode="ml"]').click();await page.waitForFunction(()=>window.mlLab?.getExperiment);
  await page.evaluate(()=>{window.__mlEvents=[];for(const kind of ['fit','predict','evaluate'])document.addEventListener(`mllab:${kind}`,event=>{window.__mlEvents.push({kind,detail:event.detail});if(window.__mlEvents.length>32)window.__mlEvents.shift();});});report.sourceFiles=await fingerprints();
  await check('managed service plus ML browser snapshot',()=>resources('loaded'));
  await check('actual grouped linear fit, saved scaling, heldout rows and prediction',async()=>{const current=await fit(fixtures.groupedDataset);assert.equal(current.model.kind,'linearRegression');for(const key of ['runId','conditionId']){const train=new Set(current.split.train.map(r=>r[key]));assert.ok(current.split.test.every(r=>!train.has(r[key])));}const predicted=await predict([{runId:'new-run',conditionId:'new-condition',features:[4],target:14}]);near(predicted.predictions,[14]);const evaluated=await predict([{runId:'new-run',conditionId:'new-condition',features:[4],target:14}],true);near(evaluated.metrics.rmse,0);assert.ok((await page.locator('#ml-model').textContent()).includes('coefficients'));assert.ok(await page.locator('#ml-plot-wrap svg').count()>0);await screenshot('linear');return{model:current.model,preprocessing:current.preprocessing,trainIds:current.split.train.map(r=>({runId:r.runId,conditionId:r.conditionId})),heldoutIds:current.split.test.map(r=>({runId:r.runId,conditionId:r.conditionId})),prediction:predicted,evaluation:evaluated};});
  await check('evaluation with reused training group IDs is explicitly descriptive',async()=>{const current=await experiment(),training=current.split.train[0];await predict([{runId:training.runId,conditionId:training.conditionId,features:[4],target:14}],true);assert.ok(/overlap.*training|training.*overlap/i.test(await page.locator('#ml-status').textContent()));assert.ok(/descriptive|not held.out/i.test(await page.locator('#ml-status').textContent()));return{runId:training.runId,conditionId:training.conditionId,status:await page.locator('#ml-status').textContent()};});
  await check('heldout edits change evaluation without changing learned parameters',async()=>{const original=await experiment(),edited=structuredClone(fixtures.groupedDataset);for(const i of original.split.testIndices){edited.records[i].features[0]+=1000;edited.records[i].target-=12345;}const changed=await fit(edited);assert.equal(canonical(changed.model),canonical(original.model));assert.equal(canonical(changed.preprocessing),canonical(original.preprocessing));assert.equal(canonical(changed.baseline),canonical(original.baseline));assert.notEqual(canonical(changed.holdout.metrics),canonical(original.holdout.metrics));return{heldoutIndices:original.split.testIndices,originalMetrics:original.holdout.metrics,changedMetrics:changed.holdout.metrics};});
  await check('changed training targets produce changed model and actual new prediction',async()=>{const before=await experiment(),edited=structuredClone(fixtures.groupedDataset);edited.records.forEach(r=>r.target+=10);const changed=await fit(edited);assert.notEqual(canonical(changed.model),canonical(before.model));near((await predict([{features:[4],runId:'new-run',conditionId:'new-condition'}])).predictions,[24]);const replay=await page.evaluate(()=>window.mlLab.replay());assert.equal(replay.matches,true);return{model:changed.model,replayMatches:true};});
  await check('classifier actually trains, predicts probabilities and evaluates confusion',async()=>{const dataset={schema:'ml-dataset.v1',sourceKind:'independent-binary-fixture',featureNames:['observableX'],targetName:'observedClass',records:Array.from({length:16},(_,i)=>({runId:`class-run-${Math.floor(i/2)}`,conditionId:`class-condition-${Math.floor(i/2)}`,features:[i-7.5],target:Number(i>=8)}))};const current=await fit(dataset,'logisticRegression',{learningRate:0.2,maxIterations:300,tolerance:1e-6});const prediction=await predict([{features:[-20],target:0,runId:'new-low',conditionId:'new-low'},{features:[20],target:1,runId:'new-high',conditionId:'new-high'}]);assert.deepEqual(prediction.labels,[0,1]);assert.ok(prediction.probabilities.every(p=>p>=0&&p<=1));const evaluation=await predict([{features:[-20],target:0,runId:'new-low',conditionId:'new-low'},{features:[20],target:1,runId:'new-high',conditionId:'new-high'}],true);assert.equal(evaluation.metrics.accuracy,1);assert.ok(evaluation.metrics.confusionMatrix);await screenshot('classifier');return{model:current.model,prediction,evaluation};});
  await check('clustering and PCA learn retained centers/directions and plot heldout points',async()=>{const dataset={schema:'ml-dataset.v1',sourceKind:'independent-cloud-fixture',featureNames:['x','y'],records:Array.from({length:12},(_,i)=>({runId:`cloud-run-${i}`,conditionId:`cloud-condition-${i}`,features:[i<6?i/10:10+i/10,i<6?i/20:10+i/20]}))};const clusters=await fit(dataset,'kMeans',{k:2,maxIterations:30,tolerance:1e-8});assert.equal(clusters.model.centroids.length,2);const prediction=await predict([{features:[0,0],runId:'new-c0',conditionId:'new-c0'},{features:[11,11],runId:'new-c1',conditionId:'new-c1'}]);assert.notEqual(prediction.assignments[0],prediction.assignments[1]);assert.ok(prediction.squaredDistances.every(v=>v>=0));const centroidMarkers=await page.locator('#ml-plot-wrap [data-centroid]').evaluateAll(nodes=>nodes.map(n=>({cluster:Number(n.dataset.centroid),transform:n.getAttribute('transform'),title:n.textContent})));assert.equal(centroidMarkers.length,2);const rawCenters=clusters.model.centroids.map(c=>c.map((v,i)=>v*clusters.preprocessing.scales[i]+clusters.preprocessing.means[i])),points=[...clusters.split.train.map(r=>r.features),[0,0],[11,11],...rawCenters],xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);for(const marker of centroidMarkers){const match=marker.transform.match(/translate\(([^ ]+) ([^)]+)\)/);const expected=rawCenters[marker.cluster];near(Number(match[1]),34+(expected[0]-Math.min(...xs))/(Math.max(...xs)-Math.min(...xs)||1)*(620-68));near(Number(match[2]),260-34-(expected[1]-Math.min(...ys))/(Math.max(...ys)-Math.min(...ys)||1)*(260-68));assert.ok(marker.title.includes('original feature units'));}await screenshot('clusters');const principal=await fit(dataset,'pca',{components:1});assert.equal(principal.model.directions.length,1);assert.ok(principal.model.converged);const projected=await predict([{features:[20,20],runId:'new-p',conditionId:'new-p'}]);assert.ok(Number.isFinite(projected.projected[0][0]));assert.ok(await page.locator('#ml-plot-wrap svg').count()>0);assert.ok((await page.locator('#ml-plot-wrap').textContent()).includes('Display order'));assert.ok((await page.locator('#ml-plot-wrap').textContent()).includes('Component 1 score (1D)'));assert.ok(await page.locator('#ml-plot-wrap .variance-bar').count()>0);await screenshot('pca');return{clusters:clusters.model,pca:principal.model,projection:projected};});
  await check('watch-derived dataset remains synthetic and baseline comparison is visible',async()=>{await page.locator('#ml-algorithm').selectOption('linearRegression');await page.locator('#ml-load-watch-data').click();await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#ml-training-input').value).sourceKind==='synthetic-watch';}catch{return false;}},{},{timeout:5000});const dataset=JSON.parse(await page.locator('#ml-training-input').inputValue());assert.equal(dataset.sourceKind,'synthetic-watch');assert.deepEqual(dataset.featureNames,['earlyObservedMechanicalHz']);for(const r of dataset.records){const o=r.observations;assert.equal(o.readoutKind,'synthetic-teaching-phase-observation');near(r.features[0],(o.earlyMechanicalCycles.numerator/o.earlyMechanicalCycles.denominator)/(2*o.earlyOperatingTime.numerator/o.earlyOperatingTime.denominator));}const current=await fit(dataset,'linearRegression',{fitIntercept:true});assert.ok(current.holdout.baselines.analytical);assert.ok((await page.locator('#ml-evaluation').textContent()).toLowerCase().includes('baseline'));assert.ok((await page.locator('#ml-provenance-detail').textContent()).includes('synthetic-watch'));await screenshot('watch-calibration');return{selectedFeatures:current.selectedFeatures,baseline:current.holdout.baselines.analytical,learnedMetrics:current.holdout.metrics};});
  await check('edited settings invalidate stale fitted-model controls',async()=>{await page.locator('#ml-seed').fill('18');await page.locator('#ml-seed').dispatchEvent('change');assert.equal(await experiment(),null);assert.ok(await page.locator('#ml-predict-button').isDisabled());assert.ok((await page.locator('#ml-model').textContent()).includes('No fitted model'));});
  await check('malformed training input produces a useful visible error',async()=>{await page.locator('#ml-training-input').fill('{');await page.locator('#ml-fit-button').click();assert.ok(/JSON|syntax|valid|Unexpected/i.test(await page.locator('#ml-status').textContent()));assert.equal(await experiment(),null);});
  await check('ML source files stayed unchanged during browser acceptance',async()=>assert.equal(canonical(await fingerprints()),canonical(report.sourceFiles)));
  await check('managed resources after ML fits and plots',()=>resources('exercised'));
  await check('no console/page errors in model UI',()=>assert.deepEqual(report.errors,[]));
}catch(error){report.checks.push({name:'ML browser registration',status:'fail',error:error.message.slice(0,3500)});}finally{await browser?.close();}
report.summary={pass:report.checks.filter(c=>c.status==='pass').length,fail:report.checks.filter(c=>c.status==='fail').length,budgetObservationOnly:true,osHardLimitEstablished:false};await writeFile(join(evidence,`ml-browser-${stamp}.json`),JSON.stringify(report,null,2)+'\n');await writeFile(join(evidence,'ml-browser-latest.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({summary:report.summary,failures:report.checks.filter(c=>c.status==='fail'),screenshots:report.screenshots,resources:report.resources.map(r=>({label:r.label,rssBytes:r.managedObservation.combinedRssBytes,budgetBytes:r.managedObservation.budgetBytes})),receipt:join(evidence,'ml-browser-latest.json')},null,2));process.exitCode=report.summary.fail?1:0;
