import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {dirname,resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../..'),product=resolve(process.env.CAPABILITY_PRODUCT_ROOT??process.argv[2]??join(root,'outputs/capability-lab'));
const evidence=resolve(process.env.CAPABILITY_EVIDENCE_ROOT??join(root,'outputs/capability-lab/evidence/independent')),fixtures=JSON.parse(await readFile(join(here,'ml-fixtures.json'),'utf8'));
const report={schema:'capability-lab.independent.ml-gate.v1',generatedAt:new Date().toISOString(),product,fixtureProvenance:fixtures.provenance,checks:[],sourceFiles:[]};
const canonical=v=>JSON.stringify(sort(v));function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
const clone=v=>structuredClone(v);function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function near(a,b,tol=1e-8){if(Array.isArray(b)){assert.ok(Array.isArray(a));assert.equal(a.length,b.length);b.forEach((v,i)=>near(a[i],v,tol));}else if(b&&typeof b==='object'){Object.keys(b).forEach(k=>near(a[k],b[k],tol));}else if(typeof b==='number'){assert.ok(Number.isFinite(a));assert.ok(Math.abs(a-b)<=tol+tol*Math.abs(b),`${a} != ${b}`);}else assert.deepEqual(a,b);}
async function check(name,family,action){const start=performance.now();try{const observed=await action();report.checks.push({name,family,status:'pass',elapsedMs:performance.now()-start,...(observed?{observed}:{})});}catch(error){report.checks.push({name,family,status:'fail',elapsedMs:performance.now()-start,error:error.message.slice(0,4000)});}}
async function snapshot(){const names=(await readdir(join(product,'src/ml'))).filter(n=>n.endsWith('.mjs')).sort();return Promise.all(names.map(async name=>{const path=join(product,'src/ml',name),bytes=await readFile(path);return{path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}));}
let api,data,regression,classification,pca,clustering,watchData;
try{[api,data,regression,classification,pca,clustering,watchData]=await Promise.all(['index','data','regression','classification','pca','clustering','watch-data'].map(name=>import(pathToFileURL(join(product,`src/ml/${name}.mjs`)))));report.sourceFiles=await snapshot();}catch(error){report.blocked={message:error.message};}
if(api&&!report.blocked){
  const run=input=>api.runMLExperiment(freeze(clone(input))),unwrapped=fit=>fit.model??fit;
  const input={dataset:clone(fixtures.groupedDataset),algorithm:'linearRegression',featureNames:['observableX'],testFraction:0.25,seed:17,standardize:true,modelConfig:{fitIntercept:true}};
  await check('hand linear coefficients and extrapolation','linear-mathematics',()=>{const f=fixtures.linear,result=regression.fitLinearRegression(freeze({features:clone(f.features),targets:clone(f.targets),fitIntercept:true})),model=unwrapped(result);near(model.intercept,f.intercept);near(model.coefficients,f.coefficients);near(regression.predictLinearRegression({model,features:f.predictionFeatures}).predictions,f.predictions);return{model,diagnostics:result.diagnostics};});
  await check('training scaler with constant feature and untouched holdout parameters','preprocessing-hand',()=>{const f=fixtures.standardizer,model=data.fitStandardizer(freeze({features:clone(f.features)}));near(model.means,f.means);near(model.scales,f.scales);assert.deepEqual(model.constantColumns,f.constantColumns);near(data.transformStandardizer({model,features:f.holdoutFeatures}).features,f.transformed);return{model,holdoutTransformed:f.transformed};});
  await check('hand residual metrics and honest constant-target R2','metrics-hand',()=>{const f=fixtures.regressionMetrics;near(data.regressionMetrics({actual:f.targets,predicted:f.predictions}),{count:f.count,mae:f.mae,mse:f.mse,rmse:f.rmse,r2:f.r2});assert.equal(data.regressionMetrics({actual:[7,7],predicted:[7,7]}).r2,null);});
  await check('stable hand logits, probabilities, boundary and extreme scores','classification-hand',()=>{const f=fixtures.logistic;near(classification.logisticScores({features:f.features,coefficients:f.coefficients,intercept:f.intercept}),f.scores);near(f.scores.map(score=>classification.logisticSigmoid({score})),f.probabilities);assert.equal(classification.logisticSigmoid({score:1000}),1);assert.equal(classification.logisticSigmoid({score:-1000}),0);near(classification.binaryCrossEntropy({scores:[0,0],targets:[0,1]}),Math.LN2);const literal={kind:'logisticRegression',version:1,coefficients:[2],intercept:-1,fitIntercept:true,threshold:0.5,training:{sampleCount:3,featureCount:1,initialization:'zeros'}};const predicted=classification.predictLogisticRegression({model:literal,features:f.features});near(predicted.scores,f.scores);near(predicted.probabilities,f.probabilities);assert.deepEqual(predicted.labels,f.labels);assert.deepEqual(classification.predictLogisticRegression({model:{...literal,coefficients:[0],intercept:0},features:[[1]]}).labels,[1]);});
  await check('logistic hand gradient and finite contradictory-label optimum','classification-training',()=>{near(classification.logisticGradient({features:[[-1],[1]],targets:[0,1],coefficients:[0],intercept:0,fitIntercept:true,l2:0}),{coefficients:[-0.5],intercept:0});const model=classification.fitLogisticRegression({features:[[-1],[-1],[-1],[-1],[1],[1],[1],[1]],targets:[0,0,0,1,1,1,1,0],learningRate:0.5,maxIterations:1000,tolerance:1e-10});near(model.coefficients,[Math.log(3)],1e-5);near(model.intercept,0,1e-8);return{model};});
  await check('classifier explicitly reports a bounded nonconverged fit','optimizer-bounds',()=>{const model=classification.fitLogisticRegression({features:[[-1],[1]],targets:[0,1],maxIterations:1,tolerance:0});assert.equal(model.optimizer.iterations,1);assert.equal(model.optimizer.converged,false);assert.throws(()=>classification.fitLogisticRegression({features:[[-1],[1]],targets:[0,1],maxIterations:10001}));});
  await check('nonzero-intercept regularized classifier ledger reports logits and BCE honestly','classification-trace-truth',()=>{const features=[[1],[2]],targets=[0,1],l2=0.5,{model,trace}=classification.fitLogisticRegressionWithTrace({features,targets,l2,maxIterations:2,learningRate:0.1});assert.notEqual(model.intercept,0);const scores=features.map(row=>row[0]*model.coefficients[0]+model.intercept),bce=scores.reduce((s,z,i)=>s+Math.max(z,0)+Math.log1p(Math.exp(-Math.abs(z)))-targets[i]*z,0)/scores.length,penalty=0.5*l2*model.coefficients.reduce((s,v)=>s+v*v,0);const final=trace.calls.filter(c=>c.phase==='final');near(final.find(c=>c.operationId==='ml.logisticScores').outputSummary.minimum,Math.min(...scores));near(final.find(c=>c.sourceId==='ml.binaryCrossEntropy').outputSummary.loss,bce);near(final.find(c=>c.operationId==='ml.regularizedObjective').outputSummary,{binaryCrossEntropy:bce,l2Penalty:penalty,objective:bce+penalty});near(model.optimizer.finalLoss,bce+penalty);return{scores,bce,l2Penalty:penalty,finalTrace:final};});
  await check('k1 hand centroid and inertia','clustering-hand',()=>{const f=fixtures.kMeansOne,model=clustering.fitKMeans({features:clone(f.features),k:1,seed:17,maxIterations:20});near(model.centroids,f.centroid);near(model.inertia,f.inertia);assert.equal(model.seed,17);assert.ok(model.converged);return{model};});
  await check('literal centroid distances and lowest-index tie','clustering-hand',()=>{const f=fixtures.kMeansPrediction,model={kind:'kmeans',featureCount:2,centroids:f.centroids,assignments:[0,1],inertia:0,iterations:1,converged:true,seed:17,config:{k:2,maxIterations:20,tolerance:1e-10,initialization:'k-means++',tieBreak:'lowest-index',emptyCluster:'retain-previous-centroid'}};const predicted=clustering.predictKMeans({model,features:f.features});assert.deepEqual(predicted.assignments,f.assignments);near(predicted.distances,f.distances);near(predicted.squaredDistances,f.squaredDistances);});
  await check('fitted PCA retains shifted training means for heldout projection','pca-hand',()=>{const f=fixtures.pca,model=pca.fitPCA({features:clone(f.features),components:2});near(model.means,f.means);near(model.eigenvalues,f.eigenvalues);near(model.explainedVarianceRatio,f.explainedVarianceRatio);assert.ok(model.converged);const result=pca.transformPCA({model,features:f.holdoutFeatures});near(result.projected.map(row=>row.map(Math.abs)),f.absoluteProjected);return{model,holdoutProjected:result.projected};});
  await check('seeded clustering retains empty centroids and reports bounded unfinished fits','clustering-policy',()=>{const duplicate={features:[[2,4],[2,4],[2,4]],k:2,seed:0,maxIterations:10};const first=clustering.fitKMeans(duplicate);assert.equal(canonical(clustering.fitKMeans(duplicate)),canonical(first));near(first.centroids,[[2,4],[2,4]]);assert.deepEqual(first.assignments,[0,0,0]);near(first.inertia,0);const unfinished=clustering.fitKMeans({features:[[0],[2]],k:1,seed:1,maxIterations:1,tolerance:0});assert.equal(unfinished.converged,false);assert.equal(unfinished.iterations,1);near(unfinished.centroids,[[1]]);near(unfinished.inertia,2);return{duplicate:first,unfinished};});
  await check('PCA rejects unfinished eigenvectors and fits refuse configured excess work','bounded-fit-work',()=>{assert.throws(()=>pca.fitPCA({features:[[0,0,0],[1,2,3],[2,1,4],[4,3,1]],maxIterations:1,tolerance:0}),/unconverged|converg/i);assert.throws(()=>pca.fitPCA({features:Array.from({length:257},(_,i)=>[i])}),/256|entries|rows/i);assert.throws(()=>clustering.fitKMeans({features:Array.from({length:501},(_,i)=>[i]),k:1,seed:1}),/500|entries|rows/i);assert.throws(()=>clustering.fitKMeans({features:Array.from({length:100},(_,i)=>[i]),k:16,seed:1,maxIterations:100}),/work|trace|calls/i);assert.throws(()=>classification.fitLogisticRegression({features:Array.from({length:200},(_,i)=>[i]),targets:Array(200).fill(0),maxIterations:10000}),/work|budget|visit/i);});
  await check('connected run and condition graph never crosses split','whole-group-splitting',()=>{const records=clone(fixtures.connectedGroupingRecords),split=data.splitByGroup({records,groupBy:'conditionId',testFraction:0.4,seed:17});for(const key of ['runId','conditionId']){const train=new Set(split.train.map(r=>r[key]));assert.ok(split.test.every(r=>!train.has(r[key])));}const connected=[0,1,2],train=new Set(split.trainIndices);assert.ok(connected.every(i=>train.has(i))||connected.every(i=>!train.has(i)));assert.deepEqual(data.splitByGroup({records,groupBy:'conditionId',testFraction:0.4,seed:17}),split);return{trainIndices:split.trainIndices,testIndices:split.testIndices,groups:split.groups};});
  await check('one connected condition/run cannot masquerade as independent holdout','whole-group-splitting',()=>{const records=[0,1,2,3].map(i=>({runId:'one-run',conditionId:`condition-${i}`,features:[i],target:i}));assert.throws(()=>data.splitByGroup({records,testFraction:0.25,seed:17}),/group|independent|connected/i);});
  await check('grouped pipeline predictions obey known line and train-only means','pipeline-mathematics',()=>{const experiment=run(input);const trainRows=experiment.split.trainIndices.map(i=>input.dataset.records[i]),trainingMean=trainRows.reduce((s,r)=>s+r.features[0],0)/trainRows.length;near(experiment.preprocessing.means,[trainingMean]);const prediction=api.predictMLModel({experiment,records:[{runId:'new',conditionId:'new',features:[4]}]});near(prediction.predictions,[14]);near(experiment.baseline.meanModel.mean,trainRows.reduce((s,r)=>s+r.target,0)/trainRows.length);for(const key of ['runId','conditionId']){const seen=new Set(experiment.split.train.map(r=>r[key]));assert.ok(experiment.split.test.every(r=>!seen.has(r[key])));}return{split:experiment.split,preprocessing:experiment.preprocessing,baseline:experiment.baseline,model:experiment.model};});
  await check('heldout-only feature/target injection cannot change learned parameters','holdout-leakage',()=>{const original=run(input),changedInput=clone(input);for(const i of original.split.testIndices){changedInput.dataset.records[i].features[0]+=1000;changedInput.dataset.records[i].target-=12345;}const changed=run(changedInput);assert.equal(canonical(changed.model),canonical(original.model));assert.equal(canonical(changed.preprocessing),canonical(original.preprocessing));assert.equal(canonical(changed.baseline),canonical(original.baseline));assert.deepEqual(changed.split.trainIndices,original.split.trainIndices);assert.notEqual(canonical(changed.holdout.metrics),canonical(original.holdout.metrics));return{heldoutIndices:original.split.testIndices,modelUnchanged:true,preprocessingUnchanged:true,holdoutMetrics:{original:original.holdout.metrics,changed:changed.holdout.metrics}};});
  await check('known hidden, target, future and identifier feature injections rejected','known-leakage-guard',()=>{for(const name of ['hiddenConfiguredFaultHz','futureClockErrorSeconds','observedY','runId']){const dataset=clone(fixtures.groupedDataset);dataset.featureNames.push(name);dataset.records.forEach(r=>r.features.push(r.target));assert.throws(()=>run({...input,dataset,featureNames:[name]}),/target|identifier|future|hidden|fault|known/i);}});
  await check('saved experiment survives original array/config and returned prediction poisoning','retained-model-integrity',()=>{const mutable=clone(input),experiment=api.runMLExperiment(mutable),before=canonical({model:experiment.model,preprocessing:experiment.preprocessing,config:experiment.config,dataset:experiment.dataset});const records=[{runId:'new',conditionId:'new',features:[4]}],first=api.predictMLModel({experiment,records});near(first.predictions,[14]);const trainingIndex=experiment.split.trainIndices[0];mutable.dataset.records[trainingIndex].features[0]=9999;mutable.dataset.records[trainingIndex].target=-9999;mutable.modelConfig.fitIntercept=false;mutable.featureNames[0]='poisoned';assert.equal(canonical({model:experiment.model,preprocessing:experiment.preprocessing,config:experiment.config,dataset:experiment.dataset}),before);near(api.predictMLModel({experiment,records}).predictions,[14]);try{first.predictions[0]=-1234;}catch(error){assert.ok(error instanceof TypeError);}near(api.predictMLModel({experiment,records}).predictions,[14]);return{trainingIndex,callerPoisoningProtected:true,predictionArrayPoisoningProtected:true};});
  await check('domain model outputs retain no mutable training-array aliases','retained-model-integrity',()=>{const cases=[{fit:regression.fitLinearRegression,predict:regression.predictLinearRegression,input:{features:clone(fixtures.linear.features),targets:clone(fixtures.linear.targets)},features:[[4]]},{fit:pca.fitPCA,predict:pca.transformPCA,input:{features:clone(fixtures.pca.features),components:2},features:[[14,20]]},{fit:clustering.fitKMeans,predict:clustering.predictKMeans,input:{features:clone(fixtures.kMeansOne.features),k:1,seed:17},features:[[2,4]]},{fit:classification.fitLogisticRegression,predict:classification.predictLogisticRegression,input:{features:[[-1],[1]],targets:[0,1],maxIterations:50},features:[[1]]}];for(const c of cases){const model=unwrapped(c.fit(c.input)),modelBefore=canonical(model),predictionBefore=canonical(c.predict({model,features:c.features}));c.input.features[0][0]=9999;if(c.input.targets)c.input.targets[0]=9999;assert.equal(canonical(model),modelBefore);assert.equal(canonical(c.predict({model,features:c.features})),predictionBefore);}});
  await check('returned domain prediction arrays cannot poison later predictions','retained-model-integrity',()=>{const cases=[{model:unwrapped(regression.fitLinearRegression({features:fixtures.linear.features,targets:fixtures.linear.targets})),predict:regression.predictLinearRegression,features:[[4]]},{model:pca.fitPCA({features:fixtures.pca.features,components:2}),predict:pca.transformPCA,features:[[14,20]]},{model:clustering.fitKMeans({features:fixtures.kMeansOne.features,k:1,seed:17}),predict:clustering.predictKMeans,features:[[2,4]]},{model:classification.fitLogisticRegression({features:[[-1],[1]],targets:[0,1],maxIterations:50}),predict:classification.predictLogisticRegression,features:[[1]]}];const poison=value=>{if(value&&typeof value==='object')for(const key of Object.keys(value)){if(typeof value[key]==='number'){try{value[key]=-9999;}catch(error){assert.ok(error instanceof TypeError);}}else poison(value[key]);}};for(const c of cases){const before=canonical(c.predict({model:c.model,features:c.features})),modelBefore=canonical(c.model),returned=c.predict({model:c.model,features:c.features});poison(returned);assert.equal(canonical(c.model),modelBefore);assert.equal(canonical(c.predict({model:c.model,features:c.features})),before);}});
  await check('complete experiment replay and model tamper rejection','canonical-replay',()=>{const experiment=run(input),replayed=api.replayMLExperiment({experiment});assert.equal(replayed.matches,true);assert.equal(canonical(replayed.fresh),canonical(experiment));const forged=clone(experiment);forged.model.coefficients[0]+=1;assert.equal(api.replayMLExperiment({experiment:forged}).matches,false);});
  await check('watch calibration uses observed API-derived feature and analytical baseline','watch-derived-data',()=>{const dataset=watchData.buildWatchCalibrationDataset({seed:17});assert.equal(dataset.sourceKind,'synthetic-watch');assert.deepEqual(dataset.featureNames,['earlyObservedMechanicalHz']);assert.equal(dataset.targetName,'horizonClockErrorSeconds');assert.ok(dataset.records.every(r=>r.observations&&r.features.length===1));const experiment=run({dataset,algorithm:'linearRegression',featureNames:dataset.featureNames,seed:17,testFraction:0.25,standardize:false});assert.ok(experiment.baseline.analyticalModel);assert.ok(experiment.holdout.baselines.analytical);assert.ok(experiment.split.train.length>0&&experiment.split.test.length>0);return{sourceKind:dataset.sourceKind,featureNames:dataset.featureNames,provenance:dataset.provenance,baseline:experiment.holdout.baselines.analytical};});
  await check('retained fine-phase watch observations independently reproduce features and later targets','watch-observation-reconstruction',async()=>{const f=fixtures.watchObservation,dataset=watchData.buildWatchCalibrationDataset(freeze({conditions:clone(f.conditions),earlySeconds:f.earlySeconds,horizonSeconds:f.horizonSeconds,seed:17})),rational=v=>v.numerator/v.denominator;assert.equal(dataset.sourceKind,'synthetic-watch');const watches=await import(pathToFileURL(join(product,'src/watches/index.mjs')));for(let i=0;i<dataset.records.length;i++){const record=dataset.records[i],o=record.observations;assert.deepEqual(o.earlyMechanicalCycles,f.earlyCycles[i]);assert.equal(o.earlyMechanicalBeats,f.earlyBeats[i]);assert.deepEqual(o.earlyObservationWindowSeconds,{numerator:5,denominator:1});assert.equal(o.readoutKind,'synthetic-teaching-phase-observation');assert.equal(o.formula,'earlyMechanicalCycles/(2*earlyOperatingTime)');near(rational(o.earlyMechanicalCycles)/(2*rational(o.earlyOperatingTime)),f.features[i]);near(record.features,[f.features[i]]);near(record.target,f.targets[i]);near(rational(o.horizonDisplayTime)-f.horizonSeconds,f.targets[i]);let state=watches.createWatchRun({mechanicalHz:4});state=watches.applyWatchAction(state,{type:'rate',model:'mechanical',hz:f.conditions[i].mechanicalHz});state=watches.applyWatchAction(state,{type:'advance',duration:5,origin:'manual'});assert.deepEqual(o.earlyMechanicalCycles,state.cycles.mechanicalBeats);state=watches.applyWatchAction(state,{type:'advance',duration:25,origin:'manual'});assert.deepEqual(o.horizonDisplayTime,state.displayTime.mechanical);}assert.equal(canonical(watchData.buildWatchCalibrationDataset({seed:17})),canonical(watchData.buildWatchCalibrationDataset({seed:17})));assert.notEqual(canonical(watchData.buildWatchCalibrationDataset({seed:18})),canonical(watchData.buildWatchCalibrationDataset({seed:17})));const poisoned=clone(dataset);poisoned.provenance.configuredConditions.forEach(c=>c.mechanicalHz={numerator:8,denominator:1});const experiment=run({dataset,algorithm:'linearRegression',seed:17,standardize:false}),changed=run({dataset:poisoned,algorithm:'linearRegression',seed:17,standardize:false});assert.equal(canonical(changed.model),canonical(experiment.model));assert.equal(canonical(changed.preprocessing),canonical(experiment.preprocessing));return{records:dataset.records,hiddenProvenancePoisoningProtected:true};});
  await check('fitted primitives reject nonfinite/ragged inputs without inventing parameters','invalid-inputs',()=>{assert.throws(()=>regression.fitLinearRegression({features:[[1],[2,3]],targets:[1,2]}));assert.throws(()=>classification.fitLogisticRegression({features:[[NaN]],targets:[1]}));assert.throws(()=>pca.fitPCA({features:[[1,2],[1,2]],components:3}));assert.throws(()=>clustering.fitKMeans({features:[[0],[1]],k:3,seed:1}));});
  await check('primitive and pipeline traces disclose genuine trainers and calls','composition-honesty',async()=>{const experiment=run(input);assert.ok(experiment.trace.calls.some(c=>c.id==='ml.fitLinearRegression'));assert.ok(experiment.trace.calls.some(c=>c.id==='ml.fitStandardizer'));assert.ok(experiment.trace.calls.length<=experiment.trace.limits.maxCalls);assert.ok(experiment.trace.bytes<=experiment.trace.limits.maxBytes);const ledger=classification.fitLogisticRegressionWithTrace({features:[[0],[1]],targets:[0,1],learningRate:0.1,maxIterations:2,l2:0.5});assert.ok(ledger.trace);report.traceExample={experiment:experiment.trace,classifier:ledger.trace};const descriptors=[...(api.capabilities??[]),...(data.capabilities??[]),...(regression.capabilities??[])];for(const descriptor of descriptors)if(/fit.*(Linear|Logistic|KMeans|PCA)|train/i.test(descriptor.id))assert.notEqual(descriptor.kind,'atomic',`complete trainer presented atomic: ${descriptor.id}`);return{pipeline:experiment.trace,classifier:ledger.trace};});
  await check('every published ML descriptor executes declared primitives and exact replay','descriptor-composition',async()=>{const [{createRegistry},stats,linalg,composed]=await Promise.all([import(pathToFileURL(join(product,'src/runtime/index.mjs'))),import(pathToFileURL(join(product,'src/statistics/index.mjs'))),import(pathToFileURL(join(product,'src/linalg/index.mjs'))),import(pathToFileURL(join(product,'src/composed/index.mjs')))]);const ml=[...(data.capabilities??[]),...(regression.capabilities??[]),...(pca.pcaCapabilities??[]),...(clustering.clusteringCapabilities??[])],all=[...stats.capabilities,...linalg.capabilities,...composed.capabilities,...ml],byId=new Map(all.map(c=>[c.id,c])),registry=createRegistry(all,{source:'independent-ml-descriptor-gate',version:'1'});const traceCheck=node=>{assert.deepEqual([...new Set(node.calls.map(c=>c.id))].sort(),[...byId.get(node.id).dependsOn].sort());node.calls.forEach(traceCheck);};const examples=[];for(const descriptor of ml){if(/fit.*(Linear|Logistic|KMeans|PCA)/i.test(descriptor.id))assert.equal(descriptor.kind,'composed');for(const example of descriptor.examples){const receipt=registry.execute(descriptor.id,freeze(clone(example.input)),{seed:17});near(receipt.result,example.expected);traceCheck(receipt.trace);assert.equal(registry.replay(receipt).matches,true);examples.push({id:descriptor.id,order:registry.get(descriptor.id).order,trace:receipt.trace});}}return{examples};});
  await check('ML sources remained unchanged during independent gate','source-provenance',async()=>assert.equal(canonical(await snapshot()),canonical(report.sourceFiles)));
}
report.summary={pass:report.checks.filter(c=>c.status==='pass').length,fail:report.checks.filter(c=>c.status==='fail').length,blocked:Boolean(report.blocked),families:[...new Set(report.checks.map(c=>c.family))]};await mkdir(evidence,{recursive:true});const stamp=report.generatedAt.replace(/[:.]/g,'-');await writeFile(join(evidence,`ml-gate-${stamp}.json`),JSON.stringify(report,null,2)+'\n');await writeFile(join(evidence,'ml-gate-latest.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({summary:report.summary,blocked:report.blocked,failures:report.checks.filter(c=>c.status==='fail'),receipt:join(evidence,'ml-gate-latest.json')},null,2));process.exitCode=report.summary.fail||report.summary.blocked?1:0;
